//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::{FromJsonQueryResult, entity::prelude::*};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "item_desc")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: i32,
    pub name: String,
    pub description: String,
    pub volume: i32,
    pub durability: i32,
    pub convert_to_on_durability_zero: i32,
    pub secondary_knowledge_id: i32,
    pub model_asset_name: String,
    pub icon_asset_name: String,
    pub tier: i32,
    pub tag: String,
    #[sea_orm(column_type = "Json")]
    pub rarity: Rarity,
    pub compendium_entry: bool,
    pub item_list_id: i32,
}

#[derive(Clone, Debug, PartialEq, FromJsonQueryResult, Deserialize, Serialize)]
pub enum Rarity {
    Default,

    Common,

    Uncommon,

    Rare,

    Epic,

    Legendary,

    Mythic,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
