// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AttackOutcomeState {
    pub entity_id: u64,
    pub last_attacked_timestamp: u64,
    pub damage: i32,
    pub crit_result: bool,
    pub dodge_result: bool,
}

impl __sdk::InModule for AttackOutcomeState {
    type Module = super::RemoteModule;
}
