// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::offset_coordinates_float_type::OffsetCoordinatesFloat;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DeployableDismountTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub deployable_entity_id: u64,
    pub player_entity_id: u64,
    pub coordinates: Option<OffsetCoordinatesFloat>,
    pub skip_deployable_icon: bool,
}

impl __sdk::InModule for DeployableDismountTimer {
    type Module = super::RemoteModule;
}
