// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::experience_stack_f_32_type::ExperienceStackF32;
use super::input_item_stack_type::InputItemStack;
use super::level_requirement_type::LevelRequirement;
use super::probabilistic_item_stack_type::ProbabilisticItemStack;
use super::tool_requirement_type::ToolRequirement;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ExtractionRecipeDesc {
    pub id: i32,
    pub resource_id: i32,
    pub cargo_id: i32,
    pub discovery_triggers: Vec<i32>,
    pub required_knowledges: Vec<i32>,
    pub time_requirement: f32,
    pub stamina_requirement: f32,
    pub tool_durability_lost: i32,
    pub extracted_item_stacks: Vec<ProbabilisticItemStack>,
    pub consumed_item_stacks: Vec<InputItemStack>,
    pub range: i32,
    pub tool_requirements: Vec<ToolRequirement>,
    pub allow_use_hands: bool,
    pub level_requirements: Vec<LevelRequirement>,
    pub experience_per_progress: Vec<ExperienceStackF32>,
    pub verb_phrase: String,
    pub tool_mesh_index: i32,
    pub recipe_performance_id: i32,
}

impl __sdk::InModule for ExtractionRecipeDesc {
    type Module = super::RemoteModule;
}
