// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::dimension_type_type::DimensionType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InteriorNetworkDesc {
    pub building_id: i32,
    pub dimension_type: DimensionType,
    pub trigger_collapse_time: u32,
    pub respawn_time: u32,
    pub child_interior_instances: Vec<i32>,
}

impl __sdk::InModule for InteriorNetworkDesc {
    type Module = super::RemoteModule;
}
