// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct NpcDesc {
    pub npc_type: i32,
    pub name: String,
    pub population: f32,
    pub speed: i32,
    pub min_time_at_ruin: i32,
    pub max_time_at_ruin: i32,
    pub prefab_address: String,
    pub icon_address: String,
    pub force_market_mode: bool,
    pub task_skill_check: Vec<i32>,
}

impl __sdk::InModule for NpcDesc {
    type Module = super::RemoteModule;
}
