// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ProgressiveActionState {
    pub entity_id: u64,
    pub building_entity_id: u64,
    pub function_type: i32,
    pub progress: i32,
    pub recipe_id: i32,
    pub craft_count: i32,
    pub last_crit_outcome: i32,
    pub owner_entity_id: u64,
    pub lock_expiration: __sdk::Timestamp,
    pub preparation: bool,
}

impl __sdk::InModule for ProgressiveActionState {
    type Module = super::RemoteModule;
}
