// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_project_site_place_request_type::PlayerProjectSitePlaceRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ProjectSitePlaceArgs {
    pub request: PlayerProjectSitePlaceRequest,
}

impl From<ProjectSitePlaceArgs> for super::Reducer {
    fn from(args: ProjectSitePlaceArgs) -> Self {
        Self::ProjectSitePlace {
            request: args.request,
        }
    }
}

impl __sdk::InModule for ProjectSitePlaceArgs {
    type Module = super::RemoteModule;
}

pub struct ProjectSitePlaceCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `project_site_place`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait project_site_place {
    /// Request that the remote module invoke the reducer `project_site_place` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_project_site_place`] callbacks.
    fn project_site_place(&self, request: PlayerProjectSitePlaceRequest) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `project_site_place`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ProjectSitePlaceCallbackId`] can be passed to [`Self::remove_on_project_site_place`]
    /// to cancel the callback.
    fn on_project_site_place(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PlayerProjectSitePlaceRequest)
        + Send
        + 'static,
    ) -> ProjectSitePlaceCallbackId;
    /// Cancel a callback previously registered by [`Self::on_project_site_place`],
    /// causing it not to run in the future.
    fn remove_on_project_site_place(&self, callback: ProjectSitePlaceCallbackId);
}

impl project_site_place for super::RemoteReducers {
    fn project_site_place(&self, request: PlayerProjectSitePlaceRequest) -> __sdk::Result<()> {
        self.imp
            .call_reducer("project_site_place", ProjectSitePlaceArgs { request })
    }
    fn on_project_site_place(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PlayerProjectSitePlaceRequest)
        + Send
        + 'static,
    ) -> ProjectSitePlaceCallbackId {
        ProjectSitePlaceCallbackId(self.imp.on_reducer(
            "project_site_place",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ProjectSitePlace { request },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, request)
            }),
        ))
    }
    fn remove_on_project_site_place(&self, callback: ProjectSitePlaceCallbackId) {
        self.imp.remove_on_reducer("project_site_place", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `project_site_place`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_project_site_place {
    /// Set the call-reducer flags for the reducer `project_site_place` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn project_site_place(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_project_site_place for super::SetReducerFlags {
    fn project_site_place(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("project_site_place", flags);
    }
}
