// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::region_connection_info_type::RegionConnectionInfo;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum RegionConnectionInfoOp {
    Insert(RegionConnectionInfo),

    Delete(RegionConnectionInfo),
}

impl __sdk::InModule for RegionConnectionInfoOp {
    type Module = super::RemoteModule;
}
