use crate::sea_orm::Statement;
use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        let db = manager.get_connection();

        let row = db.query_one(Statement::from_string(
            manager.get_database_backend(),
            "SELECT conname FROM pg_constraint WHERE conrelid = 'inventory_changelog'::regclass AND contype = 'p'".to_string(),
        )).await?;

        if let Some(row) = row {
            let pk_name: String = row.try_get("", "conname")?;
            let stmt = Statement::from_string(
                manager.get_database_backend(),
                format!("ALTER TABLE inventory_changelog DROP CONSTRAINT \"{}\";", pk_name),
            );
            db.execute(stmt).await?;
        }

        // Ensure id is auto-incrementing (Identity) if it has no default value
        let has_default = db.query_one(Statement::from_string(
            manager.get_database_backend(),
            "SELECT 1 FROM pg_attribute a
             LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = 'inventory_changelog'::regclass
             AND a.attname = 'id'
             AND (a.attidentity <> '' OR d.adbin IS NOT NULL)".to_string(),
        )).await?.is_some();

        if !has_default {
            db.execute(Statement::from_string(
                manager.get_database_backend(),
                "ALTER TABLE inventory_changelog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;".to_string(),
            )).await?;
        }

        let stmt = Statement::from_string(
            manager.get_database_backend(),
            "ALTER TABLE inventory_changelog ADD PRIMARY KEY (id, timestamp);".to_string(),
        );

        db.execute(stmt).await?;

        let stmt = Statement::from_string(
            manager.get_database_backend(),
            "SELECT create_hypertable('inventory_changelog', by_range('timestamp', INTERVAL '1 day'), migrate_data => true);".to_string(),
        );

        db.execute(stmt).await?;

        Ok(())
    }

    async fn down(&self, _manager: &SchemaManager) -> Result<(), DbErr> {
        Ok(())
    }
}
