// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AdminRestorePlayerStateTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub username: String,
    pub restore_position: bool,
    pub force_signout: bool,
    pub restore_all_deployables_positions: bool,
    pub store_deployables: bool,
    pub clear_cargo: bool,
    pub clear_items: bool,
    pub clear_toolbelt: bool,
}

impl __sdk::InModule for AdminRestorePlayerStateTimer {
    type Module = super::RemoteModule;
}
