// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminInsertResourceGrowthTimerArgs {
    pub resource_id: i32,
}

impl From<AdminInsertResourceGrowthTimerArgs> for super::Reducer {
    fn from(args: AdminInsertResourceGrowthTimerArgs) -> Self {
        Self::AdminInsertResourceGrowthTimer {
            resource_id: args.resource_id,
        }
    }
}

impl __sdk::InModule for AdminInsertResourceGrowthTimerArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_insert_resource_growth_timer`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_insert_resource_growth_timer {
    /// Request that the remote module invoke the reducer `admin_insert_resource_growth_timer` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_insert_resource_growth_timer:admin_insert_resource_growth_timer_then`] to run a callback after the reducer completes.
    fn admin_insert_resource_growth_timer(&self, resource_id: i32) -> __sdk::Result<()> {
        self.admin_insert_resource_growth_timer_then(resource_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_insert_resource_growth_timer` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_insert_resource_growth_timer_then(
        &self,
        resource_id: i32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_insert_resource_growth_timer for super::RemoteReducers {
    fn admin_insert_resource_growth_timer_then(
        &self,
        resource_id: i32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminInsertResourceGrowthTimerArgs { resource_id },
            callback,
        )
    }
}
