// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminRenameEmpireArgs {
    pub current_name: String,
    pub new_name: String,
}

impl From<AdminRenameEmpireArgs> for super::Reducer {
    fn from(args: AdminRenameEmpireArgs) -> Self {
        Self::AdminRenameEmpire {
            current_name: args.current_name,
            new_name: args.new_name,
        }
    }
}

impl __sdk::InModule for AdminRenameEmpireArgs {
    type Module = super::RemoteModule;
}

pub struct AdminRenameEmpireCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_rename_empire`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_rename_empire {
    /// Request that the remote module invoke the reducer `admin_rename_empire` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_rename_empire`] callbacks.
    fn admin_rename_empire(&self, current_name: String, new_name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_rename_empire`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminRenameEmpireCallbackId`] can be passed to [`Self::remove_on_admin_rename_empire`]
    /// to cancel the callback.
    fn on_admin_rename_empire(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> AdminRenameEmpireCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_rename_empire`],
    /// causing it not to run in the future.
    fn remove_on_admin_rename_empire(&self, callback: AdminRenameEmpireCallbackId);
}

impl admin_rename_empire for super::RemoteReducers {
    fn admin_rename_empire(&self, current_name: String, new_name: String) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "admin_rename_empire",
            AdminRenameEmpireArgs {
                current_name,
                new_name,
            },
        )
    }
    fn on_admin_rename_empire(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &String) + Send + 'static,
    ) -> AdminRenameEmpireCallbackId {
        AdminRenameEmpireCallbackId(self.imp.on_reducer(
            "admin_rename_empire",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AdminRenameEmpire {
                                    current_name,
                                    new_name,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, current_name, new_name)
            }),
        ))
    }
    fn remove_on_admin_rename_empire(&self, callback: AdminRenameEmpireCallbackId) {
        self.imp
            .remove_on_reducer("admin_rename_empire", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_rename_empire`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_rename_empire {
    /// Set the call-reducer flags for the reducer `admin_rename_empire` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_rename_empire(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_rename_empire for super::SetReducerFlags {
    fn admin_rename_empire(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("admin_rename_empire", flags);
    }
}
