// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminRenameDeployableArgs {
    pub deployable_name: String,
    pub new_name: String,
}

impl From<AdminRenameDeployableArgs> for super::Reducer {
    fn from(args: AdminRenameDeployableArgs) -> Self {
        Self::AdminRenameDeployable {
            deployable_name: args.deployable_name,
            new_name: args.new_name,
        }
    }
}

impl __sdk::InModule for AdminRenameDeployableArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_rename_deployable`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_rename_deployable {
    /// Request that the remote module invoke the reducer `admin_rename_deployable` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`admin_rename_deployable:admin_rename_deployable_then`] to run a callback after the reducer completes.
    fn admin_rename_deployable(
        &self,
        deployable_name: String,
        new_name: String,
    ) -> __sdk::Result<()> {
        self.admin_rename_deployable_then(deployable_name, new_name, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `admin_rename_deployable` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn admin_rename_deployable_then(
        &self,
        deployable_name: String,
        new_name: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl admin_rename_deployable for super::RemoteReducers {
    fn admin_rename_deployable_then(
        &self,
        deployable_name: String,
        new_name: String,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AdminRenameDeployableArgs {
                deployable_name,
                new_name,
            },
            callback,
        )
    }
}
