// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminUpdateHousingPortalsArgs {}

impl From<AdminUpdateHousingPortalsArgs> for super::Reducer {
    fn from(args: AdminUpdateHousingPortalsArgs) -> Self {
        Self::AdminUpdateHousingPortals
    }
}

impl __sdk::InModule for AdminUpdateHousingPortalsArgs {
    type Module = super::RemoteModule;
}

pub struct AdminUpdateHousingPortalsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_update_housing_portals`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_update_housing_portals {
    /// Request that the remote module invoke the reducer `admin_update_housing_portals` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_update_housing_portals`] callbacks.
    fn admin_update_housing_portals(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_update_housing_portals`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminUpdateHousingPortalsCallbackId`] can be passed to [`Self::remove_on_admin_update_housing_portals`]
    /// to cancel the callback.
    fn on_admin_update_housing_portals(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> AdminUpdateHousingPortalsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_update_housing_portals`],
    /// causing it not to run in the future.
    fn remove_on_admin_update_housing_portals(&self, callback: AdminUpdateHousingPortalsCallbackId);
}

impl admin_update_housing_portals for super::RemoteReducers {
    fn admin_update_housing_portals(&self) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "admin_update_housing_portals",
            AdminUpdateHousingPortalsArgs {},
        )
    }
    fn on_admin_update_housing_portals(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> AdminUpdateHousingPortalsCallbackId {
        AdminUpdateHousingPortalsCallbackId(self.imp.on_reducer(
            "admin_update_housing_portals",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AdminUpdateHousingPortals {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_admin_update_housing_portals(
        &self,
        callback: AdminUpdateHousingPortalsCallbackId,
    ) {
        self.imp
            .remove_on_reducer("admin_update_housing_portals", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_update_housing_portals`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_update_housing_portals {
    /// Set the call-reducer flags for the reducer `admin_update_housing_portals` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_update_housing_portals(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_update_housing_portals for super::SetReducerFlags {
    fn admin_update_housing_portals(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("admin_update_housing_portals", flags);
    }
}
