// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminDeleteAllItemsOfTypeArgs {
    pub player_username: String,
    pub item_id: i32,
    pub is_cargo: bool,
}

impl From<AdminDeleteAllItemsOfTypeArgs> for super::Reducer {
    fn from(args: AdminDeleteAllItemsOfTypeArgs) -> Self {
        Self::AdminDeleteAllItemsOfType {
            player_username: args.player_username,
            item_id: args.item_id,
            is_cargo: args.is_cargo,
        }
    }
}

impl __sdk::InModule for AdminDeleteAllItemsOfTypeArgs {
    type Module = super::RemoteModule;
}

pub struct AdminDeleteAllItemsOfTypeCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_delete_all_items_of_type`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_delete_all_items_of_type {
    /// Request that the remote module invoke the reducer `admin_delete_all_items_of_type` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_delete_all_items_of_type`] callbacks.
    fn admin_delete_all_items_of_type(
        &self,
        player_username: String,
        item_id: i32,
        is_cargo: bool,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_delete_all_items_of_type`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminDeleteAllItemsOfTypeCallbackId`] can be passed to [`Self::remove_on_admin_delete_all_items_of_type`]
    /// to cancel the callback.
    fn on_admin_delete_all_items_of_type(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String, &i32, &bool) + Send + 'static,
    ) -> AdminDeleteAllItemsOfTypeCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_delete_all_items_of_type`],
    /// causing it not to run in the future.
    fn remove_on_admin_delete_all_items_of_type(
        &self,
        callback: AdminDeleteAllItemsOfTypeCallbackId,
    );
}

impl admin_delete_all_items_of_type for super::RemoteReducers {
    fn admin_delete_all_items_of_type(
        &self,
        player_username: String,
        item_id: i32,
        is_cargo: bool,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "admin_delete_all_items_of_type",
            AdminDeleteAllItemsOfTypeArgs {
                player_username,
                item_id,
                is_cargo,
            },
        )
    }
    fn on_admin_delete_all_items_of_type(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String, &i32, &bool) + Send + 'static,
    ) -> AdminDeleteAllItemsOfTypeCallbackId {
        AdminDeleteAllItemsOfTypeCallbackId(self.imp.on_reducer(
            "admin_delete_all_items_of_type",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::AdminDeleteAllItemsOfType {
                                    player_username,
                                    item_id,
                                    is_cargo,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, player_username, item_id, is_cargo)
            }),
        ))
    }
    fn remove_on_admin_delete_all_items_of_type(
        &self,
        callback: AdminDeleteAllItemsOfTypeCallbackId,
    ) {
        self.imp
            .remove_on_reducer("admin_delete_all_items_of_type", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_delete_all_items_of_type`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_delete_all_items_of_type {
    /// Set the call-reducer flags for the reducer `admin_delete_all_items_of_type` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_delete_all_items_of_type(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_delete_all_items_of_type for super::SetReducerFlags {
    fn admin_delete_all_items_of_type(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("admin_delete_all_items_of_type", flags);
    }
}
