// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::attack_impact_event_type::AttackImpactEvent;
use super::attack_impact_timer_migrated_type::AttackImpactTimerMigrated;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `attack_impact_event`.
///
/// Obtain a handle from the [`AttackImpactEventTableAccess::attack_impact_event`] method on [`super::RemoteTables`],
/// like `ctx.db.attack_impact_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.attack_impact_event().on_insert(...)`.
pub struct AttackImpactEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<AttackImpactEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `attack_impact_event`.
pub struct AttackImpactEventTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AttackImpactEventTableAccessor {
    type Row = AttackImpactEvent;
    type Handle<'db> = AttackImpactEventTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.attack_impact_event()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `attack_impact_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AttackImpactEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AttackImpactEventTableHandle`], which mediates access to the table `attack_impact_event`.
    fn attack_impact_event(&self) -> AttackImpactEventTableHandle<'_>;
}

impl AttackImpactEventTableAccess for super::RemoteTables {
    fn attack_impact_event(&self) -> AttackImpactEventTableHandle<'_> {
        AttackImpactEventTableHandle {
            imp: self
                .imp
                .get_table::<AttackImpactEvent>("attack_impact_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AttackImpactEventInitialCallbackId(__sdk::CallbackId);
pub struct AttackImpactEventInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AttackImpactEventTableHandle<'ctx> {
    type Row = AttackImpactEvent;
    type EventContext = super::EventContext;

    __sdk::__if_client_cache! {
        fn count(&self) -> u64 { self.imp.count() }
        fn iter(&self) -> impl Iterator<Item = AttackImpactEvent> + '_ { self.imp.iter() }
    }
}

impl<'ctx> __sdk::EventTable for AttackImpactEventTableHandle<'ctx> {
    type Row = AttackImpactEvent;
    type EventContext = super::EventContext;

    __sdk::__if_client_cache! {
        fn count(&self) -> u64 { self.imp.count() }
        fn iter(&self) -> impl Iterator<Item = AttackImpactEvent> + '_ { self.imp.iter() }
    }

    type InsertCallbackId = AttackImpactEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AttackImpactEventInsertCallbackId {
        AttackImpactEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AttackImpactEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AttackImpactEventTableHandle<'ctx> {
    type InsertCallbackId = AttackImpactEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AttackImpactEventInsertCallbackId {
        AttackImpactEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AttackImpactEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

__sdk::__if_client_cache! {
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<AttackImpactEvent>("attack_impact_event");
}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AttackImpactEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AttackImpactEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AttackImpactEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait attack_impact_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AttackImpactEvent`.
    fn attack_impact_event(&self) -> __sdk::__query_builder::Table<AttackImpactEvent>;
}

impl attack_impact_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn attack_impact_event(&self) -> __sdk::__query_builder::Table<AttackImpactEvent> {
        __sdk::__query_builder::Table::new("attack_impact_event")
    }
}
