// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_barter_stall_order_delete_request_type::PlayerBarterStallOrderDeleteRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BarterStallOrderDeleteArgs {
    pub request: PlayerBarterStallOrderDeleteRequest,
}

impl From<BarterStallOrderDeleteArgs> for super::Reducer {
    fn from(args: BarterStallOrderDeleteArgs) -> Self {
        Self::BarterStallOrderDelete {
            request: args.request,
        }
    }
}

impl __sdk::InModule for BarterStallOrderDeleteArgs {
    type Module = super::RemoteModule;
}

pub struct BarterStallOrderDeleteCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `barter_stall_order_delete`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait barter_stall_order_delete {
    /// Request that the remote module invoke the reducer `barter_stall_order_delete` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_barter_stall_order_delete`] callbacks.
    fn barter_stall_order_delete(
        &self,
        request: PlayerBarterStallOrderDeleteRequest,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `barter_stall_order_delete`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`BarterStallOrderDeleteCallbackId`] can be passed to [`Self::remove_on_barter_stall_order_delete`]
    /// to cancel the callback.
    fn on_barter_stall_order_delete(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PlayerBarterStallOrderDeleteRequest)
            + Send
            + 'static,
    ) -> BarterStallOrderDeleteCallbackId;
    /// Cancel a callback previously registered by [`Self::on_barter_stall_order_delete`],
    /// causing it not to run in the future.
    fn remove_on_barter_stall_order_delete(&self, callback: BarterStallOrderDeleteCallbackId);
}

impl barter_stall_order_delete for super::RemoteReducers {
    fn barter_stall_order_delete(
        &self,
        request: PlayerBarterStallOrderDeleteRequest,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "barter_stall_order_delete",
            BarterStallOrderDeleteArgs { request },
        )
    }
    fn on_barter_stall_order_delete(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PlayerBarterStallOrderDeleteRequest)
            + Send
            + 'static,
    ) -> BarterStallOrderDeleteCallbackId {
        BarterStallOrderDeleteCallbackId(self.imp.on_reducer(
            "barter_stall_order_delete",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::BarterStallOrderDelete { request },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, request)
            }),
        ))
    }
    fn remove_on_barter_stall_order_delete(&self, callback: BarterStallOrderDeleteCallbackId) {
        self.imp
            .remove_on_reducer("barter_stall_order_delete", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `barter_stall_order_delete`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_barter_stall_order_delete {
    /// Set the call-reducer flags for the reducer `barter_stall_order_delete` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn barter_stall_order_delete(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_barter_stall_order_delete for super::SetReducerFlags {
    fn barter_stall_order_delete(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("barter_stall_order_delete", flags);
    }
}
