// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_barter_stall_order_accept_type::PlayerBarterStallOrderAccept;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BarterStallOrderAcceptArgs {
    pub request: PlayerBarterStallOrderAccept,
}

impl From<BarterStallOrderAcceptArgs> for super::Reducer {
    fn from(args: BarterStallOrderAcceptArgs) -> Self {
        Self::BarterStallOrderAccept {
            request: args.request,
        }
    }
}

impl __sdk::InModule for BarterStallOrderAcceptArgs {
    type Module = super::RemoteModule;
}

pub struct BarterStallOrderAcceptCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `barter_stall_order_accept`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait barter_stall_order_accept {
    /// Request that the remote module invoke the reducer `barter_stall_order_accept` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_barter_stall_order_accept`] callbacks.
    fn barter_stall_order_accept(&self, request: PlayerBarterStallOrderAccept)
        -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `barter_stall_order_accept`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`BarterStallOrderAcceptCallbackId`] can be passed to [`Self::remove_on_barter_stall_order_accept`]
    /// to cancel the callback.
    fn on_barter_stall_order_accept(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PlayerBarterStallOrderAccept)
            + Send
            + 'static,
    ) -> BarterStallOrderAcceptCallbackId;
    /// Cancel a callback previously registered by [`Self::on_barter_stall_order_accept`],
    /// causing it not to run in the future.
    fn remove_on_barter_stall_order_accept(&self, callback: BarterStallOrderAcceptCallbackId);
}

impl barter_stall_order_accept for super::RemoteReducers {
    fn barter_stall_order_accept(
        &self,
        request: PlayerBarterStallOrderAccept,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "barter_stall_order_accept",
            BarterStallOrderAcceptArgs { request },
        )
    }
    fn on_barter_stall_order_accept(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PlayerBarterStallOrderAccept)
            + Send
            + 'static,
    ) -> BarterStallOrderAcceptCallbackId {
        BarterStallOrderAcceptCallbackId(self.imp.on_reducer(
            "barter_stall_order_accept",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::BarterStallOrderAccept { request },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, request)
            }),
        ))
    }
    fn remove_on_barter_stall_order_accept(&self, callback: BarterStallOrderAcceptCallbackId) {
        self.imp
            .remove_on_reducer("barter_stall_order_accept", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `barter_stall_order_accept`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_barter_stall_order_accept {
    /// Set the call-reducer flags for the reducer `barter_stall_order_accept` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn barter_stall_order_accept(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_barter_stall_order_accept for super::SetReducerFlags {
    fn barter_stall_order_accept(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("barter_stall_order_accept", flags);
    }
}
