// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use super::building_claim_desc_type::BuildingClaimDesc;
use super::claim_type_type::ClaimType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `building_claim_desc`.
///
/// Obtain a handle from the [`BuildingClaimDescTableAccess::building_claim_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.building_claim_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.building_claim_desc().on_insert(...)`.
pub struct BuildingClaimDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<BuildingClaimDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `building_claim_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BuildingClaimDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BuildingClaimDescTableHandle`], which mediates access to the table `building_claim_desc`.
    fn building_claim_desc(&self) -> BuildingClaimDescTableHandle<'_>;
}

impl BuildingClaimDescTableAccess for super::RemoteTables {
    fn building_claim_desc(&self) -> BuildingClaimDescTableHandle<'_> {
        BuildingClaimDescTableHandle {
            imp: self
                .imp
                .get_table::<BuildingClaimDesc>("building_claim_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BuildingClaimDescInsertCallbackId(__sdk::CallbackId);
pub struct BuildingClaimDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BuildingClaimDescTableHandle<'ctx> {
    type Row = BuildingClaimDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BuildingClaimDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BuildingClaimDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BuildingClaimDescInsertCallbackId {
        BuildingClaimDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BuildingClaimDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BuildingClaimDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BuildingClaimDescDeleteCallbackId {
        BuildingClaimDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BuildingClaimDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BuildingClaimDesc>("building_claim_desc");
    _table.add_unique_constraint::<i32>("building_id", |row| &row.building_id);
}
pub struct BuildingClaimDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for BuildingClaimDescTableHandle<'ctx> {
    type UpdateCallbackId = BuildingClaimDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> BuildingClaimDescUpdateCallbackId {
        BuildingClaimDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: BuildingClaimDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<BuildingClaimDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BuildingClaimDesc>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `building_id` unique index on the table `building_claim_desc`,
/// which allows point queries on the field of the same name
/// via the [`BuildingClaimDescBuildingIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.building_claim_desc().building_id().find(...)`.
pub struct BuildingClaimDescBuildingIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<BuildingClaimDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> BuildingClaimDescTableHandle<'ctx> {
    /// Get a handle on the `building_id` unique index on the table `building_claim_desc`.
    pub fn building_id(&self) -> BuildingClaimDescBuildingIdUnique<'ctx> {
        BuildingClaimDescBuildingIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("building_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> BuildingClaimDescBuildingIdUnique<'ctx> {
    /// Find the subscribed row whose `building_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<BuildingClaimDesc> {
        self.imp.find(col_val)
    }
}
