// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct BuildingBuffActivateEvent {
    pub actor_entity_id: u64,
    pub building_entity_id: u64,
    pub empire_entity_id: u64,
    pub amount: u32,
}

impl __sdk::InModule for BuildingBuffActivateEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `BuildingBuffActivateEvent`.
///
/// Provides typed access to columns for query building.
pub struct BuildingBuffActivateEventCols {
    pub actor_entity_id: __sdk::__query_builder::Col<BuildingBuffActivateEvent, u64>,
    pub building_entity_id: __sdk::__query_builder::Col<BuildingBuffActivateEvent, u64>,
    pub empire_entity_id: __sdk::__query_builder::Col<BuildingBuffActivateEvent, u64>,
    pub amount: __sdk::__query_builder::Col<BuildingBuffActivateEvent, u32>,
}

impl __sdk::__query_builder::HasCols for BuildingBuffActivateEvent {
    type Cols = BuildingBuffActivateEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        BuildingBuffActivateEventCols {
            actor_entity_id: __sdk::__query_builder::Col::new(table_name, "actor_entity_id"),
            building_entity_id: __sdk::__query_builder::Col::new(table_name, "building_entity_id"),
            empire_entity_id: __sdk::__query_builder::Col::new(table_name, "empire_entity_id"),
            amount: __sdk::__query_builder::Col::new(table_name, "amount"),
        }
    }
}

/// Indexed column accessor struct for the table `BuildingBuffActivateEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct BuildingBuffActivateEventIxCols {}

impl __sdk::__query_builder::HasIxCols for BuildingBuffActivateEvent {
    type IxCols = BuildingBuffActivateEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        BuildingBuffActivateEventIxCols {}
    }
}
