// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CheatRemoveItemQuantityArgs {
    pub inventory_entity_id: u64,
    pub pocket_index: i32,
    pub quantity_to_remove: i32,
}

impl From<CheatRemoveItemQuantityArgs> for super::Reducer {
    fn from(args: CheatRemoveItemQuantityArgs) -> Self {
        Self::CheatRemoveItemQuantity {
            inventory_entity_id: args.inventory_entity_id,
            pocket_index: args.pocket_index,
            quantity_to_remove: args.quantity_to_remove,
        }
    }
}

impl __sdk::InModule for CheatRemoveItemQuantityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cheat_remove_item_quantity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cheat_remove_item_quantity {
    /// Request that the remote module invoke the reducer `cheat_remove_item_quantity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`cheat_remove_item_quantity:cheat_remove_item_quantity_then`] to run a callback after the reducer completes.
    fn cheat_remove_item_quantity(
        &self,
        inventory_entity_id: u64,
        pocket_index: i32,
        quantity_to_remove: i32,
    ) -> __sdk::Result<()> {
        self.cheat_remove_item_quantity_then(
            inventory_entity_id,
            pocket_index,
            quantity_to_remove,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `cheat_remove_item_quantity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn cheat_remove_item_quantity_then(
        &self,
        inventory_entity_id: u64,
        pocket_index: i32,
        quantity_to_remove: i32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl cheat_remove_item_quantity for super::RemoteReducers {
    fn cheat_remove_item_quantity_then(
        &self,
        inventory_entity_id: u64,
        pocket_index: i32,
        quantity_to_remove: i32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            CheatRemoveItemQuantityArgs {
                inventory_entity_id,
                pocket_index,
                quantity_to_remove,
            },
            callback,
        )
    }
}
