// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CheatEmpireSiegeCancelArgs {
    pub siege_node_entity_id: u64,
}

impl From<CheatEmpireSiegeCancelArgs> for super::Reducer {
    fn from(args: CheatEmpireSiegeCancelArgs) -> Self {
        Self::CheatEmpireSiegeCancel {
            siege_node_entity_id: args.siege_node_entity_id,
        }
    }
}

impl __sdk::InModule for CheatEmpireSiegeCancelArgs {
    type Module = super::RemoteModule;
}

pub struct CheatEmpireSiegeCancelCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cheat_empire_siege_cancel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cheat_empire_siege_cancel {
    /// Request that the remote module invoke the reducer `cheat_empire_siege_cancel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_cheat_empire_siege_cancel`] callbacks.
    fn cheat_empire_siege_cancel(&self, siege_node_entity_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `cheat_empire_siege_cancel`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CheatEmpireSiegeCancelCallbackId`] can be passed to [`Self::remove_on_cheat_empire_siege_cancel`]
    /// to cancel the callback.
    fn on_cheat_empire_siege_cancel(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> CheatEmpireSiegeCancelCallbackId;
    /// Cancel a callback previously registered by [`Self::on_cheat_empire_siege_cancel`],
    /// causing it not to run in the future.
    fn remove_on_cheat_empire_siege_cancel(&self, callback: CheatEmpireSiegeCancelCallbackId);
}

impl cheat_empire_siege_cancel for super::RemoteReducers {
    fn cheat_empire_siege_cancel(&self, siege_node_entity_id: u64) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "cheat_empire_siege_cancel",
            CheatEmpireSiegeCancelArgs {
                siege_node_entity_id,
            },
        )
    }
    fn on_cheat_empire_siege_cancel(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> CheatEmpireSiegeCancelCallbackId {
        CheatEmpireSiegeCancelCallbackId(self.imp.on_reducer(
            "cheat_empire_siege_cancel",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::CheatEmpireSiegeCancel {
                                    siege_node_entity_id,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, siege_node_entity_id)
            }),
        ))
    }
    fn remove_on_cheat_empire_siege_cancel(&self, callback: CheatEmpireSiegeCancelCallbackId) {
        self.imp
            .remove_on_reducer("cheat_empire_siege_cancel", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `cheat_empire_siege_cancel`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_cheat_empire_siege_cancel {
    /// Set the call-reducer flags for the reducer `cheat_empire_siege_cancel` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn cheat_empire_siege_cancel(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_cheat_empire_siege_cancel for super::SetReducerFlags {
    fn cheat_empire_siege_cancel(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("cheat_empire_siege_cancel", flags);
    }
}
