// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_claim_tech_cancel_request_type::PlayerClaimTechCancelRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimTechCancelArgs {
    pub request: PlayerClaimTechCancelRequest,
}

impl From<ClaimTechCancelArgs> for super::Reducer {
    fn from(args: ClaimTechCancelArgs) -> Self {
        Self::ClaimTechCancel {
            request: args.request,
        }
    }
}

impl __sdk::InModule for ClaimTechCancelArgs {
    type Module = super::RemoteModule;
}

pub struct ClaimTechCancelCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_tech_cancel`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_tech_cancel {
    /// Request that the remote module invoke the reducer `claim_tech_cancel` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_claim_tech_cancel`] callbacks.
    fn claim_tech_cancel(&self, request: PlayerClaimTechCancelRequest) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `claim_tech_cancel`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ClaimTechCancelCallbackId`] can be passed to [`Self::remove_on_claim_tech_cancel`]
    /// to cancel the callback.
    fn on_claim_tech_cancel(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PlayerClaimTechCancelRequest)
        + Send
        + 'static,
    ) -> ClaimTechCancelCallbackId;
    /// Cancel a callback previously registered by [`Self::on_claim_tech_cancel`],
    /// causing it not to run in the future.
    fn remove_on_claim_tech_cancel(&self, callback: ClaimTechCancelCallbackId);
}

impl claim_tech_cancel for super::RemoteReducers {
    fn claim_tech_cancel(&self, request: PlayerClaimTechCancelRequest) -> __sdk::Result<()> {
        self.imp
            .call_reducer("claim_tech_cancel", ClaimTechCancelArgs { request })
    }
    fn on_claim_tech_cancel(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PlayerClaimTechCancelRequest)
        + Send
        + 'static,
    ) -> ClaimTechCancelCallbackId {
        ClaimTechCancelCallbackId(self.imp.on_reducer(
            "claim_tech_cancel",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ClaimTechCancel { request },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, request)
            }),
        ))
    }
    fn remove_on_claim_tech_cancel(&self, callback: ClaimTechCancelCallbackId) {
        self.imp.remove_on_reducer("claim_tech_cancel", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `claim_tech_cancel`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_claim_tech_cancel {
    /// Set the call-reducer flags for the reducer `claim_tech_cancel` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn claim_tech_cancel(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_claim_tech_cancel for super::SetReducerFlags {
    fn claim_tech_cancel(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("claim_tech_cancel", flags);
    }
}
