// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_claim_add_member_request_type::PlayerClaimAddMemberRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimAddMemberArgs {
    pub request: PlayerClaimAddMemberRequest,
}

impl From<ClaimAddMemberArgs> for super::Reducer {
    fn from(args: ClaimAddMemberArgs) -> Self {
        Self::ClaimAddMember {
            request: args.request,
        }
    }
}

impl __sdk::InModule for ClaimAddMemberArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_add_member`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_add_member {
    /// Request that the remote module invoke the reducer `claim_add_member` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`claim_add_member:claim_add_member_then`] to run a callback after the reducer completes.
    fn claim_add_member(&self, request: PlayerClaimAddMemberRequest) -> __sdk::Result<()> {
        self.claim_add_member_then(request, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_add_member` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_add_member_then(
        &self,
        request: PlayerClaimAddMemberRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_add_member for super::RemoteReducers {
    fn claim_add_member_then(
        &self,
        request: PlayerClaimAddMemberRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ClaimAddMemberArgs { request }, callback)
    }
}
