// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use super::collect_stats_timer_type::CollectStatsTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `collect_stats_timer`.
///
/// Obtain a handle from the [`CollectStatsTimerTableAccess::collect_stats_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.collect_stats_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.collect_stats_timer().on_insert(...)`.
pub struct CollectStatsTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<CollectStatsTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `collect_stats_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CollectStatsTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CollectStatsTimerTableHandle`], which mediates access to the table `collect_stats_timer`.
    fn collect_stats_timer(&self) -> CollectStatsTimerTableHandle<'_>;
}

impl CollectStatsTimerTableAccess for super::RemoteTables {
    fn collect_stats_timer(&self) -> CollectStatsTimerTableHandle<'_> {
        CollectStatsTimerTableHandle {
            imp: self
                .imp
                .get_table::<CollectStatsTimer>("collect_stats_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CollectStatsTimerInsertCallbackId(__sdk::CallbackId);
pub struct CollectStatsTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for CollectStatsTimerTableHandle<'ctx> {
    type Row = CollectStatsTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CollectStatsTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CollectStatsTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CollectStatsTimerInsertCallbackId {
        CollectStatsTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CollectStatsTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CollectStatsTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CollectStatsTimerDeleteCallbackId {
        CollectStatsTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CollectStatsTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CollectStatsTimer>("collect_stats_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct CollectStatsTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for CollectStatsTimerTableHandle<'ctx> {
    type UpdateCallbackId = CollectStatsTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> CollectStatsTimerUpdateCallbackId {
        CollectStatsTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: CollectStatsTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<CollectStatsTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CollectStatsTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `collect_stats_timer`,
/// which allows point queries on the field of the same name
/// via the [`CollectStatsTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.collect_stats_timer().scheduled_id().find(...)`.
pub struct CollectStatsTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CollectStatsTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> CollectStatsTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `collect_stats_timer`.
    pub fn scheduled_id(&self) -> CollectStatsTimerScheduledIdUnique<'ctx> {
        CollectStatsTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> CollectStatsTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CollectStatsTimer> {
        self.imp.find(col_val)
    }
}
