// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::discovery_trigger_desc_type::DiscoveryTriggerDesc;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `construction_recipe_discovery_knowledge_desc`.
///
/// Obtain a handle from the [`ConstructionRecipeDiscoveryKnowledgeDescTableAccess::construction_recipe_discovery_knowledge_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.construction_recipe_discovery_knowledge_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.construction_recipe_discovery_knowledge_desc().on_insert(...)`.
pub struct ConstructionRecipeDiscoveryKnowledgeDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<DiscoveryTriggerDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `construction_recipe_discovery_knowledge_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ConstructionRecipeDiscoveryKnowledgeDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ConstructionRecipeDiscoveryKnowledgeDescTableHandle`], which mediates access to the table `construction_recipe_discovery_knowledge_desc`.
    fn construction_recipe_discovery_knowledge_desc(
        &self,
    ) -> ConstructionRecipeDiscoveryKnowledgeDescTableHandle<'_>;
}

impl ConstructionRecipeDiscoveryKnowledgeDescTableAccess for super::RemoteTables {
    fn construction_recipe_discovery_knowledge_desc(
        &self,
    ) -> ConstructionRecipeDiscoveryKnowledgeDescTableHandle<'_> {
        ConstructionRecipeDiscoveryKnowledgeDescTableHandle {
            imp: self
                .imp
                .get_table::<DiscoveryTriggerDesc>("construction_recipe_discovery_knowledge_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ConstructionRecipeDiscoveryKnowledgeDescInsertCallbackId(__sdk::CallbackId);
pub struct ConstructionRecipeDiscoveryKnowledgeDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ConstructionRecipeDiscoveryKnowledgeDescTableHandle<'ctx> {
    type Row = DiscoveryTriggerDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DiscoveryTriggerDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ConstructionRecipeDiscoveryKnowledgeDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConstructionRecipeDiscoveryKnowledgeDescInsertCallbackId {
        ConstructionRecipeDiscoveryKnowledgeDescInsertCallbackId(
            self.imp.on_insert(Box::new(callback)),
        )
    }

    fn remove_on_insert(&self, callback: ConstructionRecipeDiscoveryKnowledgeDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ConstructionRecipeDiscoveryKnowledgeDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ConstructionRecipeDiscoveryKnowledgeDescDeleteCallbackId {
        ConstructionRecipeDiscoveryKnowledgeDescDeleteCallbackId(
            self.imp.on_delete(Box::new(callback)),
        )
    }

    fn remove_on_delete(&self, callback: ConstructionRecipeDiscoveryKnowledgeDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<DiscoveryTriggerDesc>("construction_recipe_discovery_knowledge_desc");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DiscoveryTriggerDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DiscoveryTriggerDesc>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DiscoveryTriggerDesc`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait construction_recipe_discovery_knowledge_descQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DiscoveryTriggerDesc`.
    fn construction_recipe_discovery_knowledge_desc(
        &self,
    ) -> __sdk::__query_builder::Table<DiscoveryTriggerDesc>;
}

impl construction_recipe_discovery_knowledge_descQueryTableAccess for __sdk::QueryTableAccessor {
    fn construction_recipe_discovery_knowledge_desc(
        &self,
    ) -> __sdk::__query_builder::Table<DiscoveryTriggerDesc> {
        __sdk::__query_builder::Table::new("construction_recipe_discovery_knowledge_desc")
    }
}
