// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ContributionLootDescV2 {
    pub id: i32,
    pub enemy_type_id: i32,
    pub item_list_id: i32,
    pub minimum_contribution: i32,
    pub weighted: bool,
}

impl __sdk::InModule for ContributionLootDescV2 {
    type Module = super::RemoteModule;
}
