// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_convert_collectible_to_deed_request_type::PlayerConvertCollectibleToDeedRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ConvertCollectibleToDeedArgs {
    pub request: PlayerConvertCollectibleToDeedRequest,
}

impl From<ConvertCollectibleToDeedArgs> for super::Reducer {
    fn from(args: ConvertCollectibleToDeedArgs) -> Self {
        Self::ConvertCollectibleToDeed {
            request: args.request,
        }
    }
}

impl __sdk::InModule for ConvertCollectibleToDeedArgs {
    type Module = super::RemoteModule;
}

pub struct ConvertCollectibleToDeedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `convert_collectible_to_deed`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait convert_collectible_to_deed {
    /// Request that the remote module invoke the reducer `convert_collectible_to_deed` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_convert_collectible_to_deed`] callbacks.
    fn convert_collectible_to_deed(
        &self,
        request: PlayerConvertCollectibleToDeedRequest,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `convert_collectible_to_deed`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ConvertCollectibleToDeedCallbackId`] can be passed to [`Self::remove_on_convert_collectible_to_deed`]
    /// to cancel the callback.
    fn on_convert_collectible_to_deed(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PlayerConvertCollectibleToDeedRequest)
        + Send
        + 'static,
    ) -> ConvertCollectibleToDeedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_convert_collectible_to_deed`],
    /// causing it not to run in the future.
    fn remove_on_convert_collectible_to_deed(&self, callback: ConvertCollectibleToDeedCallbackId);
}

impl convert_collectible_to_deed for super::RemoteReducers {
    fn convert_collectible_to_deed(
        &self,
        request: PlayerConvertCollectibleToDeedRequest,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "convert_collectible_to_deed",
            ConvertCollectibleToDeedArgs { request },
        )
    }
    fn on_convert_collectible_to_deed(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PlayerConvertCollectibleToDeedRequest)
        + Send
        + 'static,
    ) -> ConvertCollectibleToDeedCallbackId {
        ConvertCollectibleToDeedCallbackId(self.imp.on_reducer(
            "convert_collectible_to_deed",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ConvertCollectibleToDeed { request },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, request)
            }),
        ))
    }
    fn remove_on_convert_collectible_to_deed(&self, callback: ConvertCollectibleToDeedCallbackId) {
        self.imp
            .remove_on_reducer("convert_collectible_to_deed", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `convert_collectible_to_deed`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_convert_collectible_to_deed {
    /// Set the call-reducer flags for the reducer `convert_collectible_to_deed` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn convert_collectible_to_deed(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_convert_collectible_to_deed for super::SetReducerFlags {
    fn convert_collectible_to_deed(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("convert_collectible_to_deed", flags);
    }
}
