// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_craft_continue_request_type::PlayerCraftContinueRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CraftContinueArgs {
    pub request: PlayerCraftContinueRequest,
}

impl From<CraftContinueArgs> for super::Reducer {
    fn from(args: CraftContinueArgs) -> Self {
        Self::CraftContinue {
            request: args.request,
        }
    }
}

impl __sdk::InModule for CraftContinueArgs {
    type Module = super::RemoteModule;
}

pub struct CraftContinueCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `craft_continue`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait craft_continue {
    /// Request that the remote module invoke the reducer `craft_continue` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_craft_continue`] callbacks.
    fn craft_continue(&self, request: PlayerCraftContinueRequest) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `craft_continue`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`CraftContinueCallbackId`] can be passed to [`Self::remove_on_craft_continue`]
    /// to cancel the callback.
    fn on_craft_continue(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PlayerCraftContinueRequest) + Send + 'static,
    ) -> CraftContinueCallbackId;
    /// Cancel a callback previously registered by [`Self::on_craft_continue`],
    /// causing it not to run in the future.
    fn remove_on_craft_continue(&self, callback: CraftContinueCallbackId);
}

impl craft_continue for super::RemoteReducers {
    fn craft_continue(&self, request: PlayerCraftContinueRequest) -> __sdk::Result<()> {
        self.imp
            .call_reducer("craft_continue", CraftContinueArgs { request })
    }
    fn on_craft_continue(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PlayerCraftContinueRequest)
            + Send
            + 'static,
    ) -> CraftContinueCallbackId {
        CraftContinueCallbackId(self.imp.on_reducer(
            "craft_continue",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::CraftContinue { request },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, request)
            }),
        ))
    }
    fn remove_on_craft_continue(&self, callback: CraftContinueCallbackId) {
        self.imp.remove_on_reducer("craft_continue", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `craft_continue`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_craft_continue {
    /// Set the call-reducer flags for the reducer `craft_continue` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn craft_continue(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_craft_continue for super::SetReducerFlags {
    fn craft_continue(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("craft_continue", flags);
    }
}
