// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::deployable_appearance_override_desc_type::DeployableAppearanceOverrideDesc;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `deployable_appearance_override_desc`.
///
/// Obtain a handle from the [`DeployableAppearanceOverrideDescTableAccess::deployable_appearance_override_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.deployable_appearance_override_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.deployable_appearance_override_desc().on_insert(...)`.
pub struct DeployableAppearanceOverrideDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<DeployableAppearanceOverrideDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `deployable_appearance_override_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DeployableAppearanceOverrideDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DeployableAppearanceOverrideDescTableHandle`], which mediates access to the table `deployable_appearance_override_desc`.
    fn deployable_appearance_override_desc(
        &self,
    ) -> DeployableAppearanceOverrideDescTableHandle<'_>;
}

impl DeployableAppearanceOverrideDescTableAccess for super::RemoteTables {
    fn deployable_appearance_override_desc(
        &self,
    ) -> DeployableAppearanceOverrideDescTableHandle<'_> {
        DeployableAppearanceOverrideDescTableHandle {
            imp: self.imp.get_table::<DeployableAppearanceOverrideDesc>(
                "deployable_appearance_override_desc",
            ),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DeployableAppearanceOverrideDescInsertCallbackId(__sdk::CallbackId);
pub struct DeployableAppearanceOverrideDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DeployableAppearanceOverrideDescTableHandle<'ctx> {
    type Row = DeployableAppearanceOverrideDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DeployableAppearanceOverrideDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DeployableAppearanceOverrideDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeployableAppearanceOverrideDescInsertCallbackId {
        DeployableAppearanceOverrideDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DeployableAppearanceOverrideDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DeployableAppearanceOverrideDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DeployableAppearanceOverrideDescDeleteCallbackId {
        DeployableAppearanceOverrideDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DeployableAppearanceOverrideDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DeployableAppearanceOverrideDesc>(
        "deployable_appearance_override_desc",
    );
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
    _table.add_unique_constraint::<i32>("collectible_id", |row| &row.collectible_id);
}
pub struct DeployableAppearanceOverrideDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DeployableAppearanceOverrideDescTableHandle<'ctx> {
    type UpdateCallbackId = DeployableAppearanceOverrideDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DeployableAppearanceOverrideDescUpdateCallbackId {
        DeployableAppearanceOverrideDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DeployableAppearanceOverrideDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DeployableAppearanceOverrideDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<DeployableAppearanceOverrideDesc>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

/// Access to the `id` unique index on the table `deployable_appearance_override_desc`,
/// which allows point queries on the field of the same name
/// via the [`DeployableAppearanceOverrideDescIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.deployable_appearance_override_desc().id().find(...)`.
pub struct DeployableAppearanceOverrideDescIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DeployableAppearanceOverrideDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DeployableAppearanceOverrideDescTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `deployable_appearance_override_desc`.
    pub fn id(&self) -> DeployableAppearanceOverrideDescIdUnique<'ctx> {
        DeployableAppearanceOverrideDescIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DeployableAppearanceOverrideDescIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<DeployableAppearanceOverrideDesc> {
        self.imp.find(col_val)
    }
}

/// Access to the `collectible_id` unique index on the table `deployable_appearance_override_desc`,
/// which allows point queries on the field of the same name
/// via the [`DeployableAppearanceOverrideDescCollectibleIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.deployable_appearance_override_desc().collectible_id().find(...)`.
pub struct DeployableAppearanceOverrideDescCollectibleIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DeployableAppearanceOverrideDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DeployableAppearanceOverrideDescTableHandle<'ctx> {
    /// Get a handle on the `collectible_id` unique index on the table `deployable_appearance_override_desc`.
    pub fn collectible_id(&self) -> DeployableAppearanceOverrideDescCollectibleIdUnique<'ctx> {
        DeployableAppearanceOverrideDescCollectibleIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("collectible_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DeployableAppearanceOverrideDescCollectibleIdUnique<'ctx> {
    /// Find the subscribed row whose `collectible_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<DeployableAppearanceOverrideDesc> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DeployableAppearanceOverrideDesc`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait deployable_appearance_override_descQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DeployableAppearanceOverrideDesc`.
    fn deployable_appearance_override_desc(
        &self,
    ) -> __sdk::__query_builder::Table<DeployableAppearanceOverrideDesc>;
}

impl deployable_appearance_override_descQueryTableAccess for __sdk::QueryTableAccessor {
    fn deployable_appearance_override_desc(
        &self,
    ) -> __sdk::__query_builder::Table<DeployableAppearanceOverrideDesc> {
        __sdk::__query_builder::Table::new("deployable_appearance_override_desc")
    }
}
