// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DeployableStateV2 {
    pub entity_id: u64,
    pub owner_id: u64,
    pub claim_entity_id: u64,
    pub direction: i32,
    pub deployable_description_id: i32,
    pub nickname: String,
    pub hidden: bool,
    pub appearance_override_id: i32,
}

impl __sdk::InModule for DeployableStateV2 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DeployableStateV2`.
///
/// Provides typed access to columns for query building.
pub struct DeployableStateV2Cols {
    pub entity_id: __sdk::__query_builder::Col<DeployableStateV2, u64>,
    pub owner_id: __sdk::__query_builder::Col<DeployableStateV2, u64>,
    pub claim_entity_id: __sdk::__query_builder::Col<DeployableStateV2, u64>,
    pub direction: __sdk::__query_builder::Col<DeployableStateV2, i32>,
    pub deployable_description_id: __sdk::__query_builder::Col<DeployableStateV2, i32>,
    pub nickname: __sdk::__query_builder::Col<DeployableStateV2, String>,
    pub hidden: __sdk::__query_builder::Col<DeployableStateV2, bool>,
    pub appearance_override_id: __sdk::__query_builder::Col<DeployableStateV2, i32>,
}

impl __sdk::__query_builder::HasCols for DeployableStateV2 {
    type Cols = DeployableStateV2Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DeployableStateV2Cols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            owner_id: __sdk::__query_builder::Col::new(table_name, "owner_id"),
            claim_entity_id: __sdk::__query_builder::Col::new(table_name, "claim_entity_id"),
            direction: __sdk::__query_builder::Col::new(table_name, "direction"),
            deployable_description_id: __sdk::__query_builder::Col::new(
                table_name,
                "deployable_description_id",
            ),
            nickname: __sdk::__query_builder::Col::new(table_name, "nickname"),
            hidden: __sdk::__query_builder::Col::new(table_name, "hidden"),
            appearance_override_id: __sdk::__query_builder::Col::new(
                table_name,
                "appearance_override_id",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `DeployableStateV2`.
///
/// Provides typed access to indexed columns for query building.
pub struct DeployableStateV2IxCols {
    pub claim_entity_id: __sdk::__query_builder::IxCol<DeployableStateV2, u64>,
    pub entity_id: __sdk::__query_builder::IxCol<DeployableStateV2, u64>,
    pub owner_id: __sdk::__query_builder::IxCol<DeployableStateV2, u64>,
}

impl __sdk::__query_builder::HasIxCols for DeployableStateV2 {
    type IxCols = DeployableStateV2IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DeployableStateV2IxCols {
            claim_entity_id: __sdk::__query_builder::IxCol::new(table_name, "claim_entity_id"),
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            owner_id: __sdk::__query_builder::IxCol::new(table_name, "owner_id"),
        }
    }
}
