// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::offset_coordinates_float_type::OffsetCoordinatesFloat;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DestroyDimensionNetworkTimer {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
    pub player_teleport_location: OffsetCoordinatesFloat,
    pub dimension_network_entity_id: u64,
}

impl __sdk::InModule for DestroyDimensionNetworkTimer {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `DestroyDimensionNetworkTimer`.
///
/// Provides typed access to columns for query building.
pub struct DestroyDimensionNetworkTimerCols {
    pub scheduled_id: __sdk::__query_builder::Col<DestroyDimensionNetworkTimer, u64>,
    pub scheduled_at: __sdk::__query_builder::Col<DestroyDimensionNetworkTimer, __sdk::ScheduleAt>,
    pub player_teleport_location:
        __sdk::__query_builder::Col<DestroyDimensionNetworkTimer, OffsetCoordinatesFloat>,
    pub dimension_network_entity_id: __sdk::__query_builder::Col<DestroyDimensionNetworkTimer, u64>,
}

impl __sdk::__query_builder::HasCols for DestroyDimensionNetworkTimer {
    type Cols = DestroyDimensionNetworkTimerCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        DestroyDimensionNetworkTimerCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
            player_teleport_location: __sdk::__query_builder::Col::new(
                table_name,
                "player_teleport_location",
            ),
            dimension_network_entity_id: __sdk::__query_builder::Col::new(
                table_name,
                "dimension_network_entity_id",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `DestroyDimensionNetworkTimer`.
///
/// Provides typed access to indexed columns for query building.
pub struct DestroyDimensionNetworkTimerIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<DestroyDimensionNetworkTimer, u64>,
}

impl __sdk::__query_builder::HasIxCols for DestroyDimensionNetworkTimer {
    type IxCols = DestroyDimensionNetworkTimerIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        DestroyDimensionNetworkTimerIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}
