// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dimension_network_state_type::DimensionNetworkState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dimension_network_state`.
///
/// Obtain a handle from the [`DimensionNetworkStateTableAccess::dimension_network_state`] method on [`super::RemoteTables`],
/// like `ctx.db.dimension_network_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dimension_network_state().on_insert(...)`.
pub struct DimensionNetworkStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<DimensionNetworkState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dimension_network_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DimensionNetworkStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DimensionNetworkStateTableHandle`], which mediates access to the table `dimension_network_state`.
    fn dimension_network_state(&self) -> DimensionNetworkStateTableHandle<'_>;
}

impl DimensionNetworkStateTableAccess for super::RemoteTables {
    fn dimension_network_state(&self) -> DimensionNetworkStateTableHandle<'_> {
        DimensionNetworkStateTableHandle {
            imp: self
                .imp
                .get_table::<DimensionNetworkState>("dimension_network_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DimensionNetworkStateInsertCallbackId(__sdk::CallbackId);
pub struct DimensionNetworkStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DimensionNetworkStateTableHandle<'ctx> {
    type Row = DimensionNetworkState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DimensionNetworkState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DimensionNetworkStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DimensionNetworkStateInsertCallbackId {
        DimensionNetworkStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DimensionNetworkStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DimensionNetworkStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DimensionNetworkStateDeleteCallbackId {
        DimensionNetworkStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DimensionNetworkStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DimensionNetworkState>("dimension_network_state");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
    _table.add_unique_constraint::<u64>("building_id", |row| &row.building_id);
}
pub struct DimensionNetworkStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DimensionNetworkStateTableHandle<'ctx> {
    type UpdateCallbackId = DimensionNetworkStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DimensionNetworkStateUpdateCallbackId {
        DimensionNetworkStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DimensionNetworkStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DimensionNetworkState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DimensionNetworkState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `entity_id` unique index on the table `dimension_network_state`,
/// which allows point queries on the field of the same name
/// via the [`DimensionNetworkStateEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dimension_network_state().entity_id().find(...)`.
pub struct DimensionNetworkStateEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DimensionNetworkState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DimensionNetworkStateTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `dimension_network_state`.
    pub fn entity_id(&self) -> DimensionNetworkStateEntityIdUnique<'ctx> {
        DimensionNetworkStateEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DimensionNetworkStateEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DimensionNetworkState> {
        self.imp.find(col_val)
    }
}

/// Access to the `building_id` unique index on the table `dimension_network_state`,
/// which allows point queries on the field of the same name
/// via the [`DimensionNetworkStateBuildingIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dimension_network_state().building_id().find(...)`.
pub struct DimensionNetworkStateBuildingIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DimensionNetworkState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DimensionNetworkStateTableHandle<'ctx> {
    /// Get a handle on the `building_id` unique index on the table `dimension_network_state`.
    pub fn building_id(&self) -> DimensionNetworkStateBuildingIdUnique<'ctx> {
        DimensionNetworkStateBuildingIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("building_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DimensionNetworkStateBuildingIdUnique<'ctx> {
    /// Find the subscribed row whose `building_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DimensionNetworkState> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DimensionNetworkState`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dimension_network_stateQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DimensionNetworkState`.
    fn dimension_network_state(&self) -> __sdk::__query_builder::Table<DimensionNetworkState>;
}

impl dimension_network_stateQueryTableAccess for __sdk::QueryTableAccessor {
    fn dimension_network_state(&self) -> __sdk::__query_builder::Table<DimensionNetworkState> {
        __sdk::__query_builder::Table::new("dimension_network_state")
    }
}
