// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DiscoverResourceArgs {
    pub resource_id: i32,
}

impl From<DiscoverResourceArgs> for super::Reducer {
    fn from(args: DiscoverResourceArgs) -> Self {
        Self::DiscoverResource {
            resource_id: args.resource_id,
        }
    }
}

impl __sdk::InModule for DiscoverResourceArgs {
    type Module = super::RemoteModule;
}

pub struct DiscoverResourceCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `discover_resource`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait discover_resource {
    /// Request that the remote module invoke the reducer `discover_resource` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_discover_resource`] callbacks.
    fn discover_resource(&self, resource_id: i32) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `discover_resource`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DiscoverResourceCallbackId`] can be passed to [`Self::remove_on_discover_resource`]
    /// to cancel the callback.
    fn on_discover_resource(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i32) + Send + 'static,
    ) -> DiscoverResourceCallbackId;
    /// Cancel a callback previously registered by [`Self::on_discover_resource`],
    /// causing it not to run in the future.
    fn remove_on_discover_resource(&self, callback: DiscoverResourceCallbackId);
}

impl discover_resource for super::RemoteReducers {
    fn discover_resource(&self, resource_id: i32) -> __sdk::Result<()> {
        self.imp
            .call_reducer("discover_resource", DiscoverResourceArgs { resource_id })
    }
    fn on_discover_resource(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i32) + Send + 'static,
    ) -> DiscoverResourceCallbackId {
        DiscoverResourceCallbackId(self.imp.on_reducer(
            "discover_resource",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DiscoverResource { resource_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, resource_id)
            }),
        ))
    }
    fn remove_on_discover_resource(&self, callback: DiscoverResourceCallbackId) {
        self.imp.remove_on_reducer("discover_resource", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `discover_resource`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_discover_resource {
    /// Set the call-reducer flags for the reducer `discover_resource` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn discover_resource(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_discover_resource for super::SetReducerFlags {
    fn discover_resource(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("discover_resource", flags);
    }
}
