// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DiscoverItemArgs {
    pub item_id: i32,
}

impl From<DiscoverItemArgs> for super::Reducer {
    fn from(args: DiscoverItemArgs) -> Self {
        Self::DiscoverItem {
            item_id: args.item_id,
        }
    }
}

impl __sdk::InModule for DiscoverItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `discover_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait discover_item {
    /// Request that the remote module invoke the reducer `discover_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`discover_item:discover_item_then`] to run a callback after the reducer completes.
    fn discover_item(&self, item_id: i32) -> __sdk::Result<()> {
        self.discover_item_then(item_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `discover_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn discover_item_then(
        &self,
        item_id: i32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl discover_item for super::RemoteReducers {
    fn discover_item_then(
        &self,
        item_id: i32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(DiscoverItemArgs { item_id }, callback)
    }
}
