// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::dropped_inventory_despawn_timer_type::DroppedInventoryDespawnTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `dropped_inventory_despawn_timer`.
///
/// Obtain a handle from the [`DroppedInventoryDespawnTimerTableAccess::dropped_inventory_despawn_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.dropped_inventory_despawn_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dropped_inventory_despawn_timer().on_insert(...)`.
pub struct DroppedInventoryDespawnTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<DroppedInventoryDespawnTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `dropped_inventory_despawn_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DroppedInventoryDespawnTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DroppedInventoryDespawnTimerTableHandle`], which mediates access to the table `dropped_inventory_despawn_timer`.
    fn dropped_inventory_despawn_timer(&self) -> DroppedInventoryDespawnTimerTableHandle<'_>;
}

impl DroppedInventoryDespawnTimerTableAccess for super::RemoteTables {
    fn dropped_inventory_despawn_timer(&self) -> DroppedInventoryDespawnTimerTableHandle<'_> {
        DroppedInventoryDespawnTimerTableHandle {
            imp: self
                .imp
                .get_table::<DroppedInventoryDespawnTimer>("dropped_inventory_despawn_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DroppedInventoryDespawnTimerInsertCallbackId(__sdk::CallbackId);
pub struct DroppedInventoryDespawnTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DroppedInventoryDespawnTimerTableHandle<'ctx> {
    type Row = DroppedInventoryDespawnTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DroppedInventoryDespawnTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DroppedInventoryDespawnTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DroppedInventoryDespawnTimerInsertCallbackId {
        DroppedInventoryDespawnTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DroppedInventoryDespawnTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DroppedInventoryDespawnTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DroppedInventoryDespawnTimerDeleteCallbackId {
        DroppedInventoryDespawnTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DroppedInventoryDespawnTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<DroppedInventoryDespawnTimer>("dropped_inventory_despawn_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct DroppedInventoryDespawnTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DroppedInventoryDespawnTimerTableHandle<'ctx> {
    type UpdateCallbackId = DroppedInventoryDespawnTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DroppedInventoryDespawnTimerUpdateCallbackId {
        DroppedInventoryDespawnTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DroppedInventoryDespawnTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DroppedInventoryDespawnTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<DroppedInventoryDespawnTimer>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `dropped_inventory_despawn_timer`,
/// which allows point queries on the field of the same name
/// via the [`DroppedInventoryDespawnTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.dropped_inventory_despawn_timer().scheduled_id().find(...)`.
pub struct DroppedInventoryDespawnTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DroppedInventoryDespawnTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DroppedInventoryDespawnTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `dropped_inventory_despawn_timer`.
    pub fn scheduled_id(&self) -> DroppedInventoryDespawnTimerScheduledIdUnique<'ctx> {
        DroppedInventoryDespawnTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DroppedInventoryDespawnTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DroppedInventoryDespawnTimer> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `DroppedInventoryDespawnTimer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait dropped_inventory_despawn_timerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `DroppedInventoryDespawnTimer`.
    fn dropped_inventory_despawn_timer(
        &self,
    ) -> __sdk::__query_builder::Table<DroppedInventoryDespawnTimer>;
}

impl dropped_inventory_despawn_timerQueryTableAccess for __sdk::QueryTableAccessor {
    fn dropped_inventory_despawn_timer(
        &self,
    ) -> __sdk::__query_builder::Table<DroppedInventoryDespawnTimer> {
        __sdk::__query_builder::Table::new("dropped_inventory_despawn_timer")
    }
}
