// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::dropped_inventory_despawn_timer_type::DroppedInventoryDespawnTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct DroppedInventoryDespawnArgs {
    pub timer: DroppedInventoryDespawnTimer,
}

impl From<DroppedInventoryDespawnArgs> for super::Reducer {
    fn from(args: DroppedInventoryDespawnArgs) -> Self {
        Self::DroppedInventoryDespawn { timer: args.timer }
    }
}

impl __sdk::InModule for DroppedInventoryDespawnArgs {
    type Module = super::RemoteModule;
}

pub struct DroppedInventoryDespawnCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `dropped_inventory_despawn`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait dropped_inventory_despawn {
    /// Request that the remote module invoke the reducer `dropped_inventory_despawn` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_dropped_inventory_despawn`] callbacks.
    fn dropped_inventory_despawn(&self, timer: DroppedInventoryDespawnTimer) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `dropped_inventory_despawn`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`DroppedInventoryDespawnCallbackId`] can be passed to [`Self::remove_on_dropped_inventory_despawn`]
    /// to cancel the callback.
    fn on_dropped_inventory_despawn(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &DroppedInventoryDespawnTimer)
        + Send
        + 'static,
    ) -> DroppedInventoryDespawnCallbackId;
    /// Cancel a callback previously registered by [`Self::on_dropped_inventory_despawn`],
    /// causing it not to run in the future.
    fn remove_on_dropped_inventory_despawn(&self, callback: DroppedInventoryDespawnCallbackId);
}

impl dropped_inventory_despawn for super::RemoteReducers {
    fn dropped_inventory_despawn(&self, timer: DroppedInventoryDespawnTimer) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "dropped_inventory_despawn",
            DroppedInventoryDespawnArgs { timer },
        )
    }
    fn on_dropped_inventory_despawn(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &DroppedInventoryDespawnTimer)
        + Send
        + 'static,
    ) -> DroppedInventoryDespawnCallbackId {
        DroppedInventoryDespawnCallbackId(self.imp.on_reducer(
            "dropped_inventory_despawn",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::DroppedInventoryDespawn { timer },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, timer)
            }),
        ))
    }
    fn remove_on_dropped_inventory_despawn(&self, callback: DroppedInventoryDespawnCallbackId) {
        self.imp
            .remove_on_reducer("dropped_inventory_despawn", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `dropped_inventory_despawn`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_dropped_inventory_despawn {
    /// Set the call-reducer flags for the reducer `dropped_inventory_despawn` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn dropped_inventory_despawn(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_dropped_inventory_despawn for super::SetReducerFlags {
    fn dropped_inventory_despawn(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("dropped_inventory_despawn", flags);
    }
}
