// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::empire_set_player_rank_request_type::EmpireSetPlayerRankRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireSetPlayerRankArgs {
    pub request: EmpireSetPlayerRankRequest,
}

impl From<EmpireSetPlayerRankArgs> for super::Reducer {
    fn from(args: EmpireSetPlayerRankArgs) -> Self {
        Self::EmpireSetPlayerRank {
            request: args.request,
        }
    }
}

impl __sdk::InModule for EmpireSetPlayerRankArgs {
    type Module = super::RemoteModule;
}

pub struct EmpireSetPlayerRankCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_set_player_rank`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_set_player_rank {
    /// Request that the remote module invoke the reducer `empire_set_player_rank` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_empire_set_player_rank`] callbacks.
    fn empire_set_player_rank(&self, request: EmpireSetPlayerRankRequest) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `empire_set_player_rank`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`EmpireSetPlayerRankCallbackId`] can be passed to [`Self::remove_on_empire_set_player_rank`]
    /// to cancel the callback.
    fn on_empire_set_player_rank(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &EmpireSetPlayerRankRequest) + Send + 'static,
    ) -> EmpireSetPlayerRankCallbackId;
    /// Cancel a callback previously registered by [`Self::on_empire_set_player_rank`],
    /// causing it not to run in the future.
    fn remove_on_empire_set_player_rank(&self, callback: EmpireSetPlayerRankCallbackId);
}

impl empire_set_player_rank for super::RemoteReducers {
    fn empire_set_player_rank(&self, request: EmpireSetPlayerRankRequest) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "empire_set_player_rank",
            EmpireSetPlayerRankArgs { request },
        )
    }
    fn on_empire_set_player_rank(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &EmpireSetPlayerRankRequest)
            + Send
            + 'static,
    ) -> EmpireSetPlayerRankCallbackId {
        EmpireSetPlayerRankCallbackId(self.imp.on_reducer(
            "empire_set_player_rank",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::EmpireSetPlayerRank { request },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, request)
            }),
        ))
    }
    fn remove_on_empire_set_player_rank(&self, callback: EmpireSetPlayerRankCallbackId) {
        self.imp
            .remove_on_reducer("empire_set_player_rank", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `empire_set_player_rank`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_empire_set_player_rank {
    /// Set the call-reducer flags for the reducer `empire_set_player_rank` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn empire_set_player_rank(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_empire_set_player_rank for super::SetReducerFlags {
    fn empire_set_player_rank(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("empire_set_player_rank", flags);
    }
}
