// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EmpireChunkState {
    pub chunk_index: u64,
    pub empire_entity_id: u64,
    pub watchtower_entity_id: u64,
}

impl __sdk::InModule for EmpireChunkState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EmpireChunkState`.
///
/// Provides typed access to columns for query building.
pub struct EmpireChunkStateCols {
    pub chunk_index: __sdk::__query_builder::Col<EmpireChunkState, u64>,
    pub empire_entity_id: __sdk::__query_builder::Col<EmpireChunkState, u64>,
    pub watchtower_entity_id: __sdk::__query_builder::Col<EmpireChunkState, u64>,
}

impl __sdk::__query_builder::HasCols for EmpireChunkState {
    type Cols = EmpireChunkStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EmpireChunkStateCols {
            chunk_index: __sdk::__query_builder::Col::new(table_name, "chunk_index"),
            empire_entity_id: __sdk::__query_builder::Col::new(table_name, "empire_entity_id"),
            watchtower_entity_id: __sdk::__query_builder::Col::new(
                table_name,
                "watchtower_entity_id",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `EmpireChunkState`.
///
/// Provides typed access to indexed columns for query building.
pub struct EmpireChunkStateIxCols {
    pub chunk_index: __sdk::__query_builder::IxCol<EmpireChunkState, u64>,
    pub empire_entity_id: __sdk::__query_builder::IxCol<EmpireChunkState, u64>,
    pub watchtower_entity_id: __sdk::__query_builder::IxCol<EmpireChunkState, u64>,
}

impl __sdk::__query_builder::HasIxCols for EmpireChunkState {
    type IxCols = EmpireChunkStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EmpireChunkStateIxCols {
            chunk_index: __sdk::__query_builder::IxCol::new(table_name, "chunk_index"),
            empire_entity_id: __sdk::__query_builder::IxCol::new(table_name, "empire_entity_id"),
            watchtower_entity_id: __sdk::__query_builder::IxCol::new(
                table_name,
                "watchtower_entity_id",
            ),
        }
    }
}
