// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EmpireLowercaseNameState {
    pub entity_id: u64,
    pub name_lowercase: String,
}

impl __sdk::InModule for EmpireLowercaseNameState {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `EmpireLowercaseNameState`.
///
/// Provides typed access to columns for query building.
pub struct EmpireLowercaseNameStateCols {
    pub entity_id: __sdk::__query_builder::Col<EmpireLowercaseNameState, u64>,
    pub name_lowercase: __sdk::__query_builder::Col<EmpireLowercaseNameState, String>,
}

impl __sdk::__query_builder::HasCols for EmpireLowercaseNameState {
    type Cols = EmpireLowercaseNameStateCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        EmpireLowercaseNameStateCols {
            entity_id: __sdk::__query_builder::Col::new(table_name, "entity_id"),
            name_lowercase: __sdk::__query_builder::Col::new(table_name, "name_lowercase"),
        }
    }
}

/// Indexed column accessor struct for the table `EmpireLowercaseNameState`.
///
/// Provides typed access to indexed columns for query building.
pub struct EmpireLowercaseNameStateIxCols {
    pub entity_id: __sdk::__query_builder::IxCol<EmpireLowercaseNameState, u64>,
    pub name_lowercase: __sdk::__query_builder::IxCol<EmpireLowercaseNameState, String>,
}

impl __sdk::__query_builder::HasIxCols for EmpireLowercaseNameState {
    type IxCols = EmpireLowercaseNameStateIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        EmpireLowercaseNameStateIxCols {
            entity_id: __sdk::__query_builder::IxCol::new(table_name, "entity_id"),
            name_lowercase: __sdk::__query_builder::IxCol::new(table_name, "name_lowercase"),
        }
    }
}
