// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::empire_create_request_type::EmpireCreateRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireCreateArgs {
    pub request: EmpireCreateRequest,
}

impl From<EmpireCreateArgs> for super::Reducer {
    fn from(args: EmpireCreateArgs) -> Self {
        Self::EmpireCreate {
            request: args.request,
        }
    }
}

impl __sdk::InModule for EmpireCreateArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_create`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_create {
    /// Request that the remote module invoke the reducer `empire_create` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`empire_create:empire_create_then`] to run a callback after the reducer completes.
    fn empire_create(&self, request: EmpireCreateRequest) -> __sdk::Result<()> {
        self.empire_create_then(request, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `empire_create` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn empire_create_then(
        &self,
        request: EmpireCreateRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl empire_create for super::RemoteReducers {
    fn empire_create_then(
        &self,
        request: EmpireCreateRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EmpireCreateArgs { request }, callback)
    }
}
