// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::offset_coordinates_small_message_type::OffsetCoordinatesSmallMessage;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EmpireSettlementState {
    pub building_entity_id: u64,
    pub claim_entity_id: u64,
    pub empire_entity_id: u64,
    pub chunk_index: u64,
    pub can_house_empire_storehouse: bool,
    pub members_donations: u32,
    pub location: OffsetCoordinatesSmallMessage,
}

impl __sdk::InModule for EmpireSettlementState {
    type Module = super::RemoteModule;
}
