// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::empire_settlement_state_type::EmpireSettlementState;
use super::offset_coordinates_small_message_type::OffsetCoordinatesSmallMessage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `empire_settlement_state`.
///
/// Obtain a handle from the [`EmpireSettlementStateTableAccess::empire_settlement_state`] method on [`super::RemoteTables`],
/// like `ctx.db.empire_settlement_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.empire_settlement_state().on_insert(...)`.
pub struct EmpireSettlementStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<EmpireSettlementState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `empire_settlement_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait EmpireSettlementStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`EmpireSettlementStateTableHandle`], which mediates access to the table `empire_settlement_state`.
    fn empire_settlement_state(&self) -> EmpireSettlementStateTableHandle<'_>;
}

impl EmpireSettlementStateTableAccess for super::RemoteTables {
    fn empire_settlement_state(&self) -> EmpireSettlementStateTableHandle<'_> {
        EmpireSettlementStateTableHandle {
            imp: self
                .imp
                .get_table::<EmpireSettlementState>("empire_settlement_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct EmpireSettlementStateInsertCallbackId(__sdk::CallbackId);
pub struct EmpireSettlementStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for EmpireSettlementStateTableHandle<'ctx> {
    type Row = EmpireSettlementState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = EmpireSettlementState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = EmpireSettlementStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EmpireSettlementStateInsertCallbackId {
        EmpireSettlementStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: EmpireSettlementStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = EmpireSettlementStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> EmpireSettlementStateDeleteCallbackId {
        EmpireSettlementStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: EmpireSettlementStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<EmpireSettlementState>("empire_settlement_state");
    _table.add_unique_constraint::<u64>("building_entity_id", |row| &row.building_entity_id);
    _table.add_unique_constraint::<u64>("claim_entity_id", |row| &row.claim_entity_id);
}
pub struct EmpireSettlementStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for EmpireSettlementStateTableHandle<'ctx> {
    type UpdateCallbackId = EmpireSettlementStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> EmpireSettlementStateUpdateCallbackId {
        EmpireSettlementStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: EmpireSettlementStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<EmpireSettlementState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<EmpireSettlementState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `building_entity_id` unique index on the table `empire_settlement_state`,
/// which allows point queries on the field of the same name
/// via the [`EmpireSettlementStateBuildingEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.empire_settlement_state().building_entity_id().find(...)`.
pub struct EmpireSettlementStateBuildingEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EmpireSettlementState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EmpireSettlementStateTableHandle<'ctx> {
    /// Get a handle on the `building_entity_id` unique index on the table `empire_settlement_state`.
    pub fn building_entity_id(&self) -> EmpireSettlementStateBuildingEntityIdUnique<'ctx> {
        EmpireSettlementStateBuildingEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("building_entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EmpireSettlementStateBuildingEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `building_entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EmpireSettlementState> {
        self.imp.find(col_val)
    }
}

/// Access to the `claim_entity_id` unique index on the table `empire_settlement_state`,
/// which allows point queries on the field of the same name
/// via the [`EmpireSettlementStateClaimEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.empire_settlement_state().claim_entity_id().find(...)`.
pub struct EmpireSettlementStateClaimEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<EmpireSettlementState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> EmpireSettlementStateTableHandle<'ctx> {
    /// Get a handle on the `claim_entity_id` unique index on the table `empire_settlement_state`.
    pub fn claim_entity_id(&self) -> EmpireSettlementStateClaimEntityIdUnique<'ctx> {
        EmpireSettlementStateClaimEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("claim_entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> EmpireSettlementStateClaimEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `claim_entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<EmpireSettlementState> {
        self.imp.find(col_val)
    }
}
