// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_equipment_add_request_type::PlayerEquipmentAddRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EquipmentAddArgs {
    pub request: PlayerEquipmentAddRequest,
}

impl From<EquipmentAddArgs> for super::Reducer {
    fn from(args: EquipmentAddArgs) -> Self {
        Self::EquipmentAdd {
            request: args.request,
        }
    }
}

impl __sdk::InModule for EquipmentAddArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `equipment_add`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait equipment_add {
    /// Request that the remote module invoke the reducer `equipment_add` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`equipment_add:equipment_add_then`] to run a callback after the reducer completes.
    fn equipment_add(&self, request: PlayerEquipmentAddRequest) -> __sdk::Result<()> {
        self.equipment_add_then(request, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `equipment_add` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn equipment_add_then(
        &self,
        request: PlayerEquipmentAddRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl equipment_add for super::RemoteReducers {
    fn equipment_add_then(
        &self,
        request: PlayerEquipmentAddRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(EquipmentAddArgs { request }, callback)
    }
}
