// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::extract_event_type::ExtractEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `extract_event`.
///
/// Obtain a handle from the [`ExtractEventTableAccess::extract_event`] method on [`super::RemoteTables`],
/// like `ctx.db.extract_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.extract_event().on_insert(...)`.
pub struct ExtractEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<ExtractEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `extract_event`.
pub struct ExtractEventTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ExtractEventTableAccessor {
    type Row = ExtractEvent;
    type Handle<'db> = ExtractEventTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.extract_event()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `extract_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ExtractEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ExtractEventTableHandle`], which mediates access to the table `extract_event`.
    fn extract_event(&self) -> ExtractEventTableHandle<'_>;
}

impl ExtractEventTableAccess for super::RemoteTables {
    fn extract_event(&self) -> ExtractEventTableHandle<'_> {
        ExtractEventTableHandle {
            imp: self.imp.get_table::<ExtractEvent>("extract_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ExtractEventInitialCallbackId(__sdk::CallbackId);
pub struct ExtractEventInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ExtractEventTableHandle<'ctx> {
    type Row = ExtractEvent;
    type EventContext = super::EventContext;

    __sdk::__if_client_cache! {
        fn count(&self) -> u64 { self.imp.count() }
        fn iter(&self) -> impl Iterator<Item = ExtractEvent> + '_ { self.imp.iter() }
    }
}

impl<'ctx> __sdk::EventTable for ExtractEventTableHandle<'ctx> {
    type Row = ExtractEvent;
    type EventContext = super::EventContext;

    __sdk::__if_client_cache! {
        fn count(&self) -> u64 { self.imp.count() }
        fn iter(&self) -> impl Iterator<Item = ExtractEvent> + '_ { self.imp.iter() }
    }

    type InsertCallbackId = ExtractEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ExtractEventInsertCallbackId {
        ExtractEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ExtractEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ExtractEventTableHandle<'ctx> {
    type InsertCallbackId = ExtractEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ExtractEventInsertCallbackId {
        ExtractEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ExtractEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

__sdk::__if_client_cache! {
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<ExtractEvent>("extract_event");
}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ExtractEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ExtractEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ExtractEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait extract_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ExtractEvent`.
    fn extract_event(&self) -> __sdk::__query_builder::Table<ExtractEvent>;
}

impl extract_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn extract_event(&self) -> __sdk::__query_builder::Table<ExtractEvent> {
        __sdk::__query_builder::Table::new("extract_event")
    }
}
