// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::premium_service_desc_type::PremiumServiceDesc;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ImportPremiumServiceDescArgs {
    pub records: Vec<PremiumServiceDesc>,
}

impl From<ImportPremiumServiceDescArgs> for super::Reducer {
    fn from(args: ImportPremiumServiceDescArgs) -> Self {
        Self::ImportPremiumServiceDesc {
            records: args.records,
        }
    }
}

impl __sdk::InModule for ImportPremiumServiceDescArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `import_premium_service_desc`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait import_premium_service_desc {
    /// Request that the remote module invoke the reducer `import_premium_service_desc` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`import_premium_service_desc:import_premium_service_desc_then`] to run a callback after the reducer completes.
    fn import_premium_service_desc(&self, records: Vec<PremiumServiceDesc>) -> __sdk::Result<()> {
        self.import_premium_service_desc_then(records, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `import_premium_service_desc` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn import_premium_service_desc_then(
        &self,
        records: Vec<PremiumServiceDesc>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl import_premium_service_desc for super::RemoteReducers {
    fn import_premium_service_desc_then(
        &self,
        records: Vec<PremiumServiceDesc>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ImportPremiumServiceDescArgs { records }, callback)
    }
}
