// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::inter_module_message_v_2_type::InterModuleMessageV2;
use super::message_contents_v_2_type::MessageContentsV2;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `inter_module_message_v2`.
///
/// Obtain a handle from the [`InterModuleMessageV2TableAccess::inter_module_message_v_2`] method on [`super::RemoteTables`],
/// like `ctx.db.inter_module_message_v_2()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inter_module_message_v_2().on_insert(...)`.
pub struct InterModuleMessageV2TableHandle<'ctx> {
    imp: __sdk::TableHandle<InterModuleMessageV2>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `inter_module_message_v2`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InterModuleMessageV2TableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InterModuleMessageV2TableHandle`], which mediates access to the table `inter_module_message_v2`.
    fn inter_module_message_v_2(&self) -> InterModuleMessageV2TableHandle<'_>;
}

impl InterModuleMessageV2TableAccess for super::RemoteTables {
    fn inter_module_message_v_2(&self) -> InterModuleMessageV2TableHandle<'_> {
        InterModuleMessageV2TableHandle {
            imp: self
                .imp
                .get_table::<InterModuleMessageV2>("inter_module_message_v2"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InterModuleMessageV2InsertCallbackId(__sdk::CallbackId);
pub struct InterModuleMessageV2DeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InterModuleMessageV2TableHandle<'ctx> {
    type Row = InterModuleMessageV2;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InterModuleMessageV2> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InterModuleMessageV2InsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InterModuleMessageV2InsertCallbackId {
        InterModuleMessageV2InsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InterModuleMessageV2InsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InterModuleMessageV2DeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InterModuleMessageV2DeleteCallbackId {
        InterModuleMessageV2DeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InterModuleMessageV2DeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InterModuleMessageV2>("inter_module_message_v2");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct InterModuleMessageV2UpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InterModuleMessageV2TableHandle<'ctx> {
    type UpdateCallbackId = InterModuleMessageV2UpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InterModuleMessageV2UpdateCallbackId {
        InterModuleMessageV2UpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InterModuleMessageV2UpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<InterModuleMessageV2>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InterModuleMessageV2>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `inter_module_message_v2`,
/// which allows point queries on the field of the same name
/// via the [`InterModuleMessageV2IdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.inter_module_message_v_2().id().find(...)`.
pub struct InterModuleMessageV2IdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InterModuleMessageV2, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InterModuleMessageV2TableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `inter_module_message_v2`.
    pub fn id(&self) -> InterModuleMessageV2IdUnique<'ctx> {
        InterModuleMessageV2IdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InterModuleMessageV2IdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<InterModuleMessageV2> {
        self.imp.find(col_val)
    }
}
