// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::enemy_type_type::EnemyType;
use super::interior_spawn_desc_type::InteriorSpawnDesc;
use super::interior_spawn_type_type::InteriorSpawnType;
use super::npc_type_type::NpcType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `interior_spawn_desc`.
///
/// Obtain a handle from the [`InteriorSpawnDescTableAccess::interior_spawn_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.interior_spawn_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.interior_spawn_desc().on_insert(...)`.
pub struct InteriorSpawnDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<InteriorSpawnDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `interior_spawn_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait InteriorSpawnDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`InteriorSpawnDescTableHandle`], which mediates access to the table `interior_spawn_desc`.
    fn interior_spawn_desc(&self) -> InteriorSpawnDescTableHandle<'_>;
}

impl InteriorSpawnDescTableAccess for super::RemoteTables {
    fn interior_spawn_desc(&self) -> InteriorSpawnDescTableHandle<'_> {
        InteriorSpawnDescTableHandle {
            imp: self
                .imp
                .get_table::<InteriorSpawnDesc>("interior_spawn_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct InteriorSpawnDescInsertCallbackId(__sdk::CallbackId);
pub struct InteriorSpawnDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for InteriorSpawnDescTableHandle<'ctx> {
    type Row = InteriorSpawnDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = InteriorSpawnDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = InteriorSpawnDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InteriorSpawnDescInsertCallbackId {
        InteriorSpawnDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: InteriorSpawnDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = InteriorSpawnDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> InteriorSpawnDescDeleteCallbackId {
        InteriorSpawnDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: InteriorSpawnDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<InteriorSpawnDesc>("interior_spawn_desc");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}
pub struct InteriorSpawnDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for InteriorSpawnDescTableHandle<'ctx> {
    type UpdateCallbackId = InteriorSpawnDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> InteriorSpawnDescUpdateCallbackId {
        InteriorSpawnDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: InteriorSpawnDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<InteriorSpawnDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<InteriorSpawnDesc>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `interior_spawn_desc`,
/// which allows point queries on the field of the same name
/// via the [`InteriorSpawnDescIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.interior_spawn_desc().id().find(...)`.
pub struct InteriorSpawnDescIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<InteriorSpawnDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> InteriorSpawnDescTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `interior_spawn_desc`.
    pub fn id(&self) -> InteriorSpawnDescIdUnique<'ctx> {
        InteriorSpawnDescIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> InteriorSpawnDescIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<InteriorSpawnDesc> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `InteriorSpawnDesc`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait interior_spawn_descQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `InteriorSpawnDesc`.
    fn interior_spawn_desc(&self) -> __sdk::__query_builder::Table<InteriorSpawnDesc>;
}

impl interior_spawn_descQueryTableAccess for __sdk::QueryTableAccessor {
    fn interior_spawn_desc(&self) -> __sdk::__query_builder::Table<InteriorSpawnDesc> {
        __sdk::__query_builder::Table::new("interior_spawn_desc")
    }
}
