// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::message_contents_v_2_type::MessageContentsV2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct InterModuleMessageV2 {
    pub id: u64,
    pub to: u8,
    pub contents: MessageContentsV2,
}

impl __sdk::InModule for InterModuleMessageV2 {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `InterModuleMessageV2`.
///
/// Provides typed access to columns for query building.
pub struct InterModuleMessageV2Cols {
    pub id: __sdk::__query_builder::Col<InterModuleMessageV2, u64>,
    pub to: __sdk::__query_builder::Col<InterModuleMessageV2, u8>,
    pub contents: __sdk::__query_builder::Col<InterModuleMessageV2, MessageContentsV2>,
}

impl __sdk::__query_builder::HasCols for InterModuleMessageV2 {
    type Cols = InterModuleMessageV2Cols;
    fn cols(table_name: &'static str) -> Self::Cols {
        InterModuleMessageV2Cols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            to: __sdk::__query_builder::Col::new(table_name, "to"),
            contents: __sdk::__query_builder::Col::new(table_name, "contents"),
        }
    }
}

/// Indexed column accessor struct for the table `InterModuleMessageV2`.
///
/// Provides typed access to indexed columns for query building.
pub struct InterModuleMessageV2IxCols {
    pub id: __sdk::__query_builder::IxCol<InterModuleMessageV2, u64>,
}

impl __sdk::__query_builder::HasIxCols for InterModuleMessageV2 {
    type IxCols = InterModuleMessageV2IxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        InterModuleMessageV2IxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}
