// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_item_convert_request_type::PlayerItemConvertRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ItemConvertStartEvent {
    pub actor_id: u64,
    pub request: PlayerItemConvertRequest,
}

impl __sdk::InModule for ItemConvertStartEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ItemConvertStartEvent`.
///
/// Provides typed access to columns for query building.
pub struct ItemConvertStartEventCols {
    pub actor_id: __sdk::__query_builder::Col<ItemConvertStartEvent, u64>,
    pub request: __sdk::__query_builder::Col<ItemConvertStartEvent, PlayerItemConvertRequest>,
}

impl __sdk::__query_builder::HasCols for ItemConvertStartEvent {
    type Cols = ItemConvertStartEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ItemConvertStartEventCols {
            actor_id: __sdk::__query_builder::Col::new(table_name, "actor_id"),
            request: __sdk::__query_builder::Col::new(table_name, "request"),
        }
    }
}

/// Indexed column accessor struct for the table `ItemConvertStartEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct ItemConvertStartEventIxCols {}

impl __sdk::__query_builder::HasIxCols for ItemConvertStartEvent {
    type IxCols = ItemConvertStartEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ItemConvertStartEventIxCols {}
    }
}
