// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_item_convert_request_type::PlayerItemConvertRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ItemConvertArgs {
    pub request: PlayerItemConvertRequest,
}

impl From<ItemConvertArgs> for super::Reducer {
    fn from(args: ItemConvertArgs) -> Self {
        Self::ItemConvert {
            request: args.request,
        }
    }
}

impl __sdk::InModule for ItemConvertArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `item_convert`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait item_convert {
    /// Request that the remote module invoke the reducer `item_convert` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`item_convert:item_convert_then`] to run a callback after the reducer completes.
    fn item_convert(&self, request: PlayerItemConvertRequest) -> __sdk::Result<()> {
        self.item_convert_then(request, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `item_convert` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn item_convert_then(
        &self,
        request: PlayerItemConvertRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl item_convert for super::RemoteReducers {
    fn item_convert_then(
        &self,
        request: PlayerItemConvertRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ItemConvertArgs { request }, callback)
    }
}
