// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::item_list_desc_type::ItemListDesc;
use super::item_list_possibility_type::ItemListPossibility;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `item_list_desc`.
///
/// Obtain a handle from the [`ItemListDescTableAccess::item_list_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.item_list_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item_list_desc().on_insert(...)`.
pub struct ItemListDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<ItemListDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `item_list_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ItemListDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ItemListDescTableHandle`], which mediates access to the table `item_list_desc`.
    fn item_list_desc(&self) -> ItemListDescTableHandle<'_>;
}

impl ItemListDescTableAccess for super::RemoteTables {
    fn item_list_desc(&self) -> ItemListDescTableHandle<'_> {
        ItemListDescTableHandle {
            imp: self.imp.get_table::<ItemListDesc>("item_list_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ItemListDescInsertCallbackId(__sdk::CallbackId);
pub struct ItemListDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ItemListDescTableHandle<'ctx> {
    type Row = ItemListDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ItemListDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ItemListDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemListDescInsertCallbackId {
        ItemListDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ItemListDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ItemListDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ItemListDescDeleteCallbackId {
        ItemListDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ItemListDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ItemListDesc>("item_list_desc");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}
pub struct ItemListDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ItemListDescTableHandle<'ctx> {
    type UpdateCallbackId = ItemListDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ItemListDescUpdateCallbackId {
        ItemListDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ItemListDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ItemListDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ItemListDesc>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `item_list_desc`,
/// which allows point queries on the field of the same name
/// via the [`ItemListDescIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.item_list_desc().id().find(...)`.
pub struct ItemListDescIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ItemListDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ItemListDescTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `item_list_desc`.
    pub fn id(&self) -> ItemListDescIdUnique<'ctx> {
        ItemListDescIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ItemListDescIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<ItemListDesc> {
        self.imp.find(col_val)
    }
}
