// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use super::knowledge_scroll_type_desc_type::KnowledgeScrollTypeDesc;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `knowledge_scroll_type_desc`.
///
/// Obtain a handle from the [`KnowledgeScrollTypeDescTableAccess::knowledge_scroll_type_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.knowledge_scroll_type_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.knowledge_scroll_type_desc().on_insert(...)`.
pub struct KnowledgeScrollTypeDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<KnowledgeScrollTypeDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `knowledge_scroll_type_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait KnowledgeScrollTypeDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`KnowledgeScrollTypeDescTableHandle`], which mediates access to the table `knowledge_scroll_type_desc`.
    fn knowledge_scroll_type_desc(&self) -> KnowledgeScrollTypeDescTableHandle<'_>;
}

impl KnowledgeScrollTypeDescTableAccess for super::RemoteTables {
    fn knowledge_scroll_type_desc(&self) -> KnowledgeScrollTypeDescTableHandle<'_> {
        KnowledgeScrollTypeDescTableHandle {
            imp: self
                .imp
                .get_table::<KnowledgeScrollTypeDesc>("knowledge_scroll_type_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct KnowledgeScrollTypeDescInsertCallbackId(__sdk::CallbackId);
pub struct KnowledgeScrollTypeDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for KnowledgeScrollTypeDescTableHandle<'ctx> {
    type Row = KnowledgeScrollTypeDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = KnowledgeScrollTypeDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = KnowledgeScrollTypeDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnowledgeScrollTypeDescInsertCallbackId {
        KnowledgeScrollTypeDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: KnowledgeScrollTypeDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = KnowledgeScrollTypeDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> KnowledgeScrollTypeDescDeleteCallbackId {
        KnowledgeScrollTypeDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: KnowledgeScrollTypeDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<KnowledgeScrollTypeDesc>("knowledge_scroll_type_desc");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}
pub struct KnowledgeScrollTypeDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for KnowledgeScrollTypeDescTableHandle<'ctx> {
    type UpdateCallbackId = KnowledgeScrollTypeDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> KnowledgeScrollTypeDescUpdateCallbackId {
        KnowledgeScrollTypeDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: KnowledgeScrollTypeDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<KnowledgeScrollTypeDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<KnowledgeScrollTypeDesc>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `knowledge_scroll_type_desc`,
/// which allows point queries on the field of the same name
/// via the [`KnowledgeScrollTypeDescIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.knowledge_scroll_type_desc().id().find(...)`.
pub struct KnowledgeScrollTypeDescIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<KnowledgeScrollTypeDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> KnowledgeScrollTypeDescTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `knowledge_scroll_type_desc`.
    pub fn id(&self) -> KnowledgeScrollTypeDescIdUnique<'ctx> {
        KnowledgeScrollTypeDescIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> KnowledgeScrollTypeDescIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<KnowledgeScrollTypeDesc> {
        self.imp.find(col_val)
    }
}
