// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MigrateCharacterStatsArgs {}

impl From<MigrateCharacterStatsArgs> for super::Reducer {
    fn from(args: MigrateCharacterStatsArgs) -> Self {
        Self::MigrateCharacterStats
    }
}

impl __sdk::InModule for MigrateCharacterStatsArgs {
    type Module = super::RemoteModule;
}

pub struct MigrateCharacterStatsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `migrate_character_stats`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait migrate_character_stats {
    /// Request that the remote module invoke the reducer `migrate_character_stats` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_migrate_character_stats`] callbacks.
    fn migrate_character_stats(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `migrate_character_stats`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`MigrateCharacterStatsCallbackId`] can be passed to [`Self::remove_on_migrate_character_stats`]
    /// to cancel the callback.
    fn on_migrate_character_stats(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> MigrateCharacterStatsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_migrate_character_stats`],
    /// causing it not to run in the future.
    fn remove_on_migrate_character_stats(&self, callback: MigrateCharacterStatsCallbackId);
}

impl migrate_character_stats for super::RemoteReducers {
    fn migrate_character_stats(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("migrate_character_stats", MigrateCharacterStatsArgs {})
    }
    fn on_migrate_character_stats(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> MigrateCharacterStatsCallbackId {
        MigrateCharacterStatsCallbackId(self.imp.on_reducer(
            "migrate_character_stats",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::MigrateCharacterStats {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_migrate_character_stats(&self, callback: MigrateCharacterStatsCallbackId) {
        self.imp
            .remove_on_reducer("migrate_character_stats", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `migrate_character_stats`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_migrate_character_stats {
    /// Set the call-reducer flags for the reducer `migrate_character_stats` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn migrate_character_stats(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_migrate_character_stats for super::SetReducerFlags {
    fn migrate_character_stats(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("migrate_character_stats", flags);
    }
}
