// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::csv_stat_entry_type::CsvStatEntry;
use super::experience_stack_f_32_type::ExperienceStackF32;
use super::input_item_stack_type::InputItemStack;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PavingTileDesc {
    pub id: i32,
    pub name: String,
    pub consumed_item_stacks: Vec<InputItemStack>,
    pub input_cargo_id: i32,
    pub input_cargo_discovery_score: i32,
    pub experience_per_progress: Vec<ExperienceStackF32>,
    pub discovery_triggers: Vec<i32>,
    pub required_knowledges: Vec<i32>,
    pub full_discovery_score: i32,
    pub paving_duration: f32,
    pub prefab_address: String,
    pub tier: i32,
    pub stat_effects: Vec<CsvStatEntry>,
    pub icon_address: String,
    pub description: String,
}

impl __sdk::InModule for PavingTileDesc {
    type Module = super::RemoteModule;
}
