// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_paving_destroy_tile_request_type::PlayerPavingDestroyTileRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PavingDestroyTileStartArgs {
    pub request: PlayerPavingDestroyTileRequest,
}

impl From<PavingDestroyTileStartArgs> for super::Reducer {
    fn from(args: PavingDestroyTileStartArgs) -> Self {
        Self::PavingDestroyTileStart {
            request: args.request,
        }
    }
}

impl __sdk::InModule for PavingDestroyTileStartArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `paving_destroy_tile_start`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait paving_destroy_tile_start {
    /// Request that the remote module invoke the reducer `paving_destroy_tile_start` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`paving_destroy_tile_start:paving_destroy_tile_start_then`] to run a callback after the reducer completes.
    fn paving_destroy_tile_start(
        &self,
        request: PlayerPavingDestroyTileRequest,
    ) -> __sdk::Result<()> {
        self.paving_destroy_tile_start_then(request, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `paving_destroy_tile_start` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn paving_destroy_tile_start_then(
        &self,
        request: PlayerPavingDestroyTileRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl paving_destroy_tile_start for super::RemoteReducers {
    fn paving_destroy_tile_start_then(
        &self,
        request: PlayerPavingDestroyTileRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PavingDestroyTileStartArgs { request }, callback)
    }
}
