// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_pillar_shaping_place_request_type::PlayerPillarShapingPlaceRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PillarShapingPlacePillarStartEvent {
    pub actor_id: u64,
    pub request: PlayerPillarShapingPlaceRequest,
}

impl __sdk::InModule for PillarShapingPlacePillarStartEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PillarShapingPlacePillarStartEvent`.
///
/// Provides typed access to columns for query building.
pub struct PillarShapingPlacePillarStartEventCols {
    pub actor_id: __sdk::__query_builder::Col<PillarShapingPlacePillarStartEvent, u64>,
    pub request: __sdk::__query_builder::Col<
        PillarShapingPlacePillarStartEvent,
        PlayerPillarShapingPlaceRequest,
    >,
}

impl __sdk::__query_builder::HasCols for PillarShapingPlacePillarStartEvent {
    type Cols = PillarShapingPlacePillarStartEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PillarShapingPlacePillarStartEventCols {
            actor_id: __sdk::__query_builder::Col::new(table_name, "actor_id"),
            request: __sdk::__query_builder::Col::new(table_name, "request"),
        }
    }
}

/// Indexed column accessor struct for the table `PillarShapingPlacePillarStartEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct PillarShapingPlacePillarStartEventIxCols {}

impl __sdk::__query_builder::HasIxCols for PillarShapingPlacePillarStartEvent {
    type IxCols = PillarShapingPlacePillarStartEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PillarShapingPlacePillarStartEventIxCols {}
    }
}
