// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_pillar_shaping_place_request_type::PlayerPillarShapingPlaceRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PillarShapingPlacePillarStartArgs {
    pub request: PlayerPillarShapingPlaceRequest,
}

impl From<PillarShapingPlacePillarStartArgs> for super::Reducer {
    fn from(args: PillarShapingPlacePillarStartArgs) -> Self {
        Self::PillarShapingPlacePillarStart {
            request: args.request,
        }
    }
}

impl __sdk::InModule for PillarShapingPlacePillarStartArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `pillar_shaping_place_pillar_start`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait pillar_shaping_place_pillar_start {
    /// Request that the remote module invoke the reducer `pillar_shaping_place_pillar_start` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`pillar_shaping_place_pillar_start:pillar_shaping_place_pillar_start_then`] to run a callback after the reducer completes.
    fn pillar_shaping_place_pillar_start(
        &self,
        request: PlayerPillarShapingPlaceRequest,
    ) -> __sdk::Result<()> {
        self.pillar_shaping_place_pillar_start_then(request, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `pillar_shaping_place_pillar_start` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn pillar_shaping_place_pillar_start_then(
        &self,
        request: PlayerPillarShapingPlaceRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl pillar_shaping_place_pillar_start for super::RemoteReducers {
    fn pillar_shaping_place_pillar_start_then(
        &self,
        request: PlayerPillarShapingPlaceRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PillarShapingPlacePillarStartArgs { request }, callback)
    }
}
