// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_pillar_shaping_destroy_request_type::PlayerPillarShapingDestroyRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PillarShapingDestroyStartEvent {
    pub actor_id: u64,
    pub request: PlayerPillarShapingDestroyRequest,
}

impl __sdk::InModule for PillarShapingDestroyStartEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PillarShapingDestroyStartEvent`.
///
/// Provides typed access to columns for query building.
pub struct PillarShapingDestroyStartEventCols {
    pub actor_id: __sdk::__query_builder::Col<PillarShapingDestroyStartEvent, u64>,
    pub request: __sdk::__query_builder::Col<
        PillarShapingDestroyStartEvent,
        PlayerPillarShapingDestroyRequest,
    >,
}

impl __sdk::__query_builder::HasCols for PillarShapingDestroyStartEvent {
    type Cols = PillarShapingDestroyStartEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PillarShapingDestroyStartEventCols {
            actor_id: __sdk::__query_builder::Col::new(table_name, "actor_id"),
            request: __sdk::__query_builder::Col::new(table_name, "request"),
        }
    }
}

/// Indexed column accessor struct for the table `PillarShapingDestroyStartEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct PillarShapingDestroyStartEventIxCols {}

impl __sdk::__query_builder::HasIxCols for PillarShapingDestroyStartEvent {
    type IxCols = PillarShapingDestroyStartEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PillarShapingDestroyStartEventIxCols {}
    }
}
