// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::placeable_interact_start_event_type::PlaceableInteractStartEvent;
use super::player_placeable_interact_request_type::PlayerPlaceableInteractRequest;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `placeable_interact_start_event`.
///
/// Obtain a handle from the [`PlaceableInteractStartEventTableAccess::placeable_interact_start_event`] method on [`super::RemoteTables`],
/// like `ctx.db.placeable_interact_start_event()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.placeable_interact_start_event().on_insert(...)`.
pub struct PlaceableInteractStartEventTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlaceableInteractStartEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `placeable_interact_start_event`.
pub struct PlaceableInteractStartEventTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for PlaceableInteractStartEventTableAccessor {
    type Row = PlaceableInteractStartEvent;
    type Handle<'db> = PlaceableInteractStartEventTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.placeable_interact_start_event()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `placeable_interact_start_event`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlaceableInteractStartEventTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlaceableInteractStartEventTableHandle`], which mediates access to the table `placeable_interact_start_event`.
    fn placeable_interact_start_event(&self) -> PlaceableInteractStartEventTableHandle<'_>;
}

impl PlaceableInteractStartEventTableAccess for super::RemoteTables {
    fn placeable_interact_start_event(&self) -> PlaceableInteractStartEventTableHandle<'_> {
        PlaceableInteractStartEventTableHandle {
            imp: self
                .imp
                .get_table::<PlaceableInteractStartEvent>("placeable_interact_start_event"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlaceableInteractStartEventInitialCallbackId(__sdk::CallbackId);
pub struct PlaceableInteractStartEventInsertCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for PlaceableInteractStartEventTableHandle<'ctx> {
    type Row = PlaceableInteractStartEvent;
    type EventContext = super::EventContext;

    __sdk::__if_client_cache! {
        fn count(&self) -> u64 { self.imp.count() }
        fn iter(&self) -> impl Iterator<Item = PlaceableInteractStartEvent> + '_ { self.imp.iter() }
    }
}

impl<'ctx> __sdk::EventTable for PlaceableInteractStartEventTableHandle<'ctx> {
    type Row = PlaceableInteractStartEvent;
    type EventContext = super::EventContext;

    __sdk::__if_client_cache! {
        fn count(&self) -> u64 { self.imp.count() }
        fn iter(&self) -> impl Iterator<Item = PlaceableInteractStartEvent> + '_ { self.imp.iter() }
    }

    type InsertCallbackId = PlaceableInteractStartEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlaceableInteractStartEventInsertCallbackId {
        PlaceableInteractStartEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlaceableInteractStartEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for PlaceableInteractStartEventTableHandle<'ctx> {
    type InsertCallbackId = PlaceableInteractStartEventInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlaceableInteractStartEventInsertCallbackId {
        PlaceableInteractStartEventInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlaceableInteractStartEventInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

__sdk::__if_client_cache! {
#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {

        let _table = client_cache.get_or_make_table::<PlaceableInteractStartEvent>("placeable_interact_start_event");
}
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<PlaceableInteractStartEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<PlaceableInteractStartEvent>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `PlaceableInteractStartEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait placeable_interact_start_eventQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `PlaceableInteractStartEvent`.
    fn placeable_interact_start_event(
        &self,
    ) -> __sdk::__query_builder::Table<PlaceableInteractStartEvent>;
}

impl placeable_interact_start_eventQueryTableAccess for __sdk::QueryTableAccessor {
    fn placeable_interact_start_event(
        &self,
    ) -> __sdk::__query_builder::Table<PlaceableInteractStartEvent> {
        __sdk::__query_builder::Table::new("placeable_interact_start_event")
    }
}
