// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_action_desc_type::PlayerActionDesc;
use super::player_action_layer_type::PlayerActionLayer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_action_desc`.
///
/// Obtain a handle from the [`PlayerActionDescTableAccess::player_action_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.player_action_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_action_desc().on_insert(...)`.
pub struct PlayerActionDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerActionDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_action_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerActionDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerActionDescTableHandle`], which mediates access to the table `player_action_desc`.
    fn player_action_desc(&self) -> PlayerActionDescTableHandle<'_>;
}

impl PlayerActionDescTableAccess for super::RemoteTables {
    fn player_action_desc(&self) -> PlayerActionDescTableHandle<'_> {
        PlayerActionDescTableHandle {
            imp: self.imp.get_table::<PlayerActionDesc>("player_action_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerActionDescInsertCallbackId(__sdk::CallbackId);
pub struct PlayerActionDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerActionDescTableHandle<'ctx> {
    type Row = PlayerActionDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerActionDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerActionDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerActionDescInsertCallbackId {
        PlayerActionDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerActionDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerActionDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerActionDescDeleteCallbackId {
        PlayerActionDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerActionDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<PlayerActionDesc>("player_action_desc");
    _table.add_unique_constraint::<i32>("action_type_id", |row| &row.action_type_id);
}
pub struct PlayerActionDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerActionDescTableHandle<'ctx> {
    type UpdateCallbackId = PlayerActionDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerActionDescUpdateCallbackId {
        PlayerActionDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerActionDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerActionDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerActionDesc>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `action_type_id` unique index on the table `player_action_desc`,
/// which allows point queries on the field of the same name
/// via the [`PlayerActionDescActionTypeIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_action_desc().action_type_id().find(...)`.
pub struct PlayerActionDescActionTypeIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerActionDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerActionDescTableHandle<'ctx> {
    /// Get a handle on the `action_type_id` unique index on the table `player_action_desc`.
    pub fn action_type_id(&self) -> PlayerActionDescActionTypeIdUnique<'ctx> {
        PlayerActionDescActionTypeIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("action_type_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerActionDescActionTypeIdUnique<'ctx> {
    /// Find the subscribed row whose `action_type_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<PlayerActionDesc> {
        self.imp.find(col_val)
    }
}
