// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::item_type_type::ItemType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerPostOrderRequest {
    pub building_entity_id: u64,
    pub item_id: i32,
    pub item_type: ItemType,
    pub max_unit_price: i32,
    pub quantity: i32,
    pub persist_order: bool,
    pub coins_spent: i32,
}

impl __sdk::InModule for PlayerPostOrderRequest {
    type Module = super::RemoteModule;
}
