// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_dismiss_alert_request_type::PlayerDismissAlertRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerDismissAlertArgs {
    pub request: PlayerDismissAlertRequest,
}

impl From<PlayerDismissAlertArgs> for super::Reducer {
    fn from(args: PlayerDismissAlertArgs) -> Self {
        Self::PlayerDismissAlert {
            request: args.request,
        }
    }
}

impl __sdk::InModule for PlayerDismissAlertArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerDismissAlertCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_dismiss_alert`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_dismiss_alert {
    /// Request that the remote module invoke the reducer `player_dismiss_alert` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_dismiss_alert`] callbacks.
    fn player_dismiss_alert(&self, request: PlayerDismissAlertRequest) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_dismiss_alert`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerDismissAlertCallbackId`] can be passed to [`Self::remove_on_player_dismiss_alert`]
    /// to cancel the callback.
    fn on_player_dismiss_alert(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PlayerDismissAlertRequest) + Send + 'static,
    ) -> PlayerDismissAlertCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_dismiss_alert`],
    /// causing it not to run in the future.
    fn remove_on_player_dismiss_alert(&self, callback: PlayerDismissAlertCallbackId);
}

impl player_dismiss_alert for super::RemoteReducers {
    fn player_dismiss_alert(&self, request: PlayerDismissAlertRequest) -> __sdk::Result<()> {
        self.imp
            .call_reducer("player_dismiss_alert", PlayerDismissAlertArgs { request })
    }
    fn on_player_dismiss_alert(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PlayerDismissAlertRequest)
        + Send
        + 'static,
    ) -> PlayerDismissAlertCallbackId {
        PlayerDismissAlertCallbackId(self.imp.on_reducer(
            "player_dismiss_alert",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PlayerDismissAlert { request },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, request)
            }),
        ))
    }
    fn remove_on_player_dismiss_alert(&self, callback: PlayerDismissAlertCallbackId) {
        self.imp
            .remove_on_reducer("player_dismiss_alert", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_dismiss_alert`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_dismiss_alert {
    /// Set the call-reducer flags for the reducer `player_dismiss_alert` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_dismiss_alert(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_dismiss_alert for super::SetReducerFlags {
    fn player_dismiss_alert(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("player_dismiss_alert", flags);
    }
}
