// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use super::player_vote_conclude_timer_type::PlayerVoteConcludeTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_vote_conclude_timer`.
///
/// Obtain a handle from the [`PlayerVoteConcludeTimerTableAccess::player_vote_conclude_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.player_vote_conclude_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_vote_conclude_timer().on_insert(...)`.
pub struct PlayerVoteConcludeTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerVoteConcludeTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_vote_conclude_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerVoteConcludeTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerVoteConcludeTimerTableHandle`], which mediates access to the table `player_vote_conclude_timer`.
    fn player_vote_conclude_timer(&self) -> PlayerVoteConcludeTimerTableHandle<'_>;
}

impl PlayerVoteConcludeTimerTableAccess for super::RemoteTables {
    fn player_vote_conclude_timer(&self) -> PlayerVoteConcludeTimerTableHandle<'_> {
        PlayerVoteConcludeTimerTableHandle {
            imp: self
                .imp
                .get_table::<PlayerVoteConcludeTimer>("player_vote_conclude_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerVoteConcludeTimerInsertCallbackId(__sdk::CallbackId);
pub struct PlayerVoteConcludeTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerVoteConcludeTimerTableHandle<'ctx> {
    type Row = PlayerVoteConcludeTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerVoteConcludeTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerVoteConcludeTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerVoteConcludeTimerInsertCallbackId {
        PlayerVoteConcludeTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerVoteConcludeTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerVoteConcludeTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerVoteConcludeTimerDeleteCallbackId {
        PlayerVoteConcludeTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerVoteConcludeTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<PlayerVoteConcludeTimer>("player_vote_conclude_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct PlayerVoteConcludeTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerVoteConcludeTimerTableHandle<'ctx> {
    type UpdateCallbackId = PlayerVoteConcludeTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerVoteConcludeTimerUpdateCallbackId {
        PlayerVoteConcludeTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerVoteConcludeTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerVoteConcludeTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<PlayerVoteConcludeTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `player_vote_conclude_timer`,
/// which allows point queries on the field of the same name
/// via the [`PlayerVoteConcludeTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_vote_conclude_timer().scheduled_id().find(...)`.
pub struct PlayerVoteConcludeTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerVoteConcludeTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerVoteConcludeTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `player_vote_conclude_timer`.
    pub fn scheduled_id(&self) -> PlayerVoteConcludeTimerScheduledIdUnique<'ctx> {
        PlayerVoteConcludeTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerVoteConcludeTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PlayerVoteConcludeTimer> {
        self.imp.find(col_val)
    }
}
