// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::player_housing_moving_cost_state_type::PlayerHousingMovingCostState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `player_housing_moving_cost_state`.
///
/// Obtain a handle from the [`PlayerHousingMovingCostStateTableAccess::player_housing_moving_cost_state`] method on [`super::RemoteTables`],
/// like `ctx.db.player_housing_moving_cost_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_housing_moving_cost_state().on_insert(...)`.
pub struct PlayerHousingMovingCostStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<PlayerHousingMovingCostState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `player_housing_moving_cost_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait PlayerHousingMovingCostStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`PlayerHousingMovingCostStateTableHandle`], which mediates access to the table `player_housing_moving_cost_state`.
    fn player_housing_moving_cost_state(&self) -> PlayerHousingMovingCostStateTableHandle<'_>;
}

impl PlayerHousingMovingCostStateTableAccess for super::RemoteTables {
    fn player_housing_moving_cost_state(&self) -> PlayerHousingMovingCostStateTableHandle<'_> {
        PlayerHousingMovingCostStateTableHandle {
            imp: self
                .imp
                .get_table::<PlayerHousingMovingCostState>("player_housing_moving_cost_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct PlayerHousingMovingCostStateInsertCallbackId(__sdk::CallbackId);
pub struct PlayerHousingMovingCostStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for PlayerHousingMovingCostStateTableHandle<'ctx> {
    type Row = PlayerHousingMovingCostState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = PlayerHousingMovingCostState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = PlayerHousingMovingCostStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerHousingMovingCostStateInsertCallbackId {
        PlayerHousingMovingCostStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: PlayerHousingMovingCostStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = PlayerHousingMovingCostStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> PlayerHousingMovingCostStateDeleteCallbackId {
        PlayerHousingMovingCostStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: PlayerHousingMovingCostStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<PlayerHousingMovingCostState>("player_housing_moving_cost_state");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}
pub struct PlayerHousingMovingCostStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for PlayerHousingMovingCostStateTableHandle<'ctx> {
    type UpdateCallbackId = PlayerHousingMovingCostStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> PlayerHousingMovingCostStateUpdateCallbackId {
        PlayerHousingMovingCostStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: PlayerHousingMovingCostStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<PlayerHousingMovingCostState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<PlayerHousingMovingCostState>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

/// Access to the `entity_id` unique index on the table `player_housing_moving_cost_state`,
/// which allows point queries on the field of the same name
/// via the [`PlayerHousingMovingCostStateEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.player_housing_moving_cost_state().entity_id().find(...)`.
pub struct PlayerHousingMovingCostStateEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<PlayerHousingMovingCostState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> PlayerHousingMovingCostStateTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `player_housing_moving_cost_state`.
    pub fn entity_id(&self) -> PlayerHousingMovingCostStateEntityIdUnique<'ctx> {
        PlayerHousingMovingCostStateEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> PlayerHousingMovingCostStateEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<PlayerHousingMovingCostState> {
        self.imp.find(col_val)
    }
}
