// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_death_timer_type::PlayerDeathTimer;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerDeathStartEvent {
    pub actor_id: u64,
    pub timer: PlayerDeathTimer,
}

impl __sdk::InModule for PlayerDeathStartEvent {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `PlayerDeathStartEvent`.
///
/// Provides typed access to columns for query building.
pub struct PlayerDeathStartEventCols {
    pub actor_id: __sdk::__query_builder::Col<PlayerDeathStartEvent, u64>,
    pub timer: __sdk::__query_builder::Col<PlayerDeathStartEvent, PlayerDeathTimer>,
}

impl __sdk::__query_builder::HasCols for PlayerDeathStartEvent {
    type Cols = PlayerDeathStartEventCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        PlayerDeathStartEventCols {
            actor_id: __sdk::__query_builder::Col::new(table_name, "actor_id"),
            timer: __sdk::__query_builder::Col::new(table_name, "timer"),
        }
    }
}

/// Indexed column accessor struct for the table `PlayerDeathStartEvent`.
///
/// Provides typed access to indexed columns for query building.
pub struct PlayerDeathStartEventIxCols {}

impl __sdk::__query_builder::HasIxCols for PlayerDeathStartEvent {
    type IxCols = PlayerDeathStartEventIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        PlayerDeathStartEventIxCols {}
    }
}
