// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerCreateArgs {}

impl From<PlayerCreateArgs> for super::Reducer {
    fn from(args: PlayerCreateArgs) -> Self {
        Self::PlayerCreate
    }
}

impl __sdk::InModule for PlayerCreateArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerCreateCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_create`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_create {
    /// Request that the remote module invoke the reducer `player_create` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_create`] callbacks.
    fn player_create(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_create`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerCreateCallbackId`] can be passed to [`Self::remove_on_player_create`]
    /// to cancel the callback.
    fn on_player_create(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> PlayerCreateCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_create`],
    /// causing it not to run in the future.
    fn remove_on_player_create(&self, callback: PlayerCreateCallbackId);
}

impl player_create for super::RemoteReducers {
    fn player_create(&self) -> __sdk::Result<()> {
        self.imp.call_reducer("player_create", PlayerCreateArgs {})
    }
    fn on_player_create(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> PlayerCreateCallbackId {
        PlayerCreateCallbackId(self.imp.on_reducer(
            "player_create",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PlayerCreate {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_player_create(&self, callback: PlayerCreateCallbackId) {
        self.imp.remove_on_reducer("player_create", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_create`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_create {
    /// Set the call-reducer flags for the reducer `player_create` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_create(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_create for super::SetReducerFlags {
    fn player_create(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("player_create", flags);
    }
}
