// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_teleport_waystone_request_type::PlayerTeleportWaystoneRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerTeleportWaystoneStartArgs {
    pub request: PlayerTeleportWaystoneRequest,
}

impl From<PlayerTeleportWaystoneStartArgs> for super::Reducer {
    fn from(args: PlayerTeleportWaystoneStartArgs) -> Self {
        Self::PlayerTeleportWaystoneStart {
            request: args.request,
        }
    }
}

impl __sdk::InModule for PlayerTeleportWaystoneStartArgs {
    type Module = super::RemoteModule;
}

pub struct PlayerTeleportWaystoneStartCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_teleport_waystone_start`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_teleport_waystone_start {
    /// Request that the remote module invoke the reducer `player_teleport_waystone_start` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_player_teleport_waystone_start`] callbacks.
    fn player_teleport_waystone_start(
        &self,
        request: PlayerTeleportWaystoneRequest,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `player_teleport_waystone_start`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`PlayerTeleportWaystoneStartCallbackId`] can be passed to [`Self::remove_on_player_teleport_waystone_start`]
    /// to cancel the callback.
    fn on_player_teleport_waystone_start(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &PlayerTeleportWaystoneRequest)
        + Send
        + 'static,
    ) -> PlayerTeleportWaystoneStartCallbackId;
    /// Cancel a callback previously registered by [`Self::on_player_teleport_waystone_start`],
    /// causing it not to run in the future.
    fn remove_on_player_teleport_waystone_start(
        &self,
        callback: PlayerTeleportWaystoneStartCallbackId,
    );
}

impl player_teleport_waystone_start for super::RemoteReducers {
    fn player_teleport_waystone_start(
        &self,
        request: PlayerTeleportWaystoneRequest,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "player_teleport_waystone_start",
            PlayerTeleportWaystoneStartArgs { request },
        )
    }
    fn on_player_teleport_waystone_start(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &PlayerTeleportWaystoneRequest)
        + Send
        + 'static,
    ) -> PlayerTeleportWaystoneStartCallbackId {
        PlayerTeleportWaystoneStartCallbackId(self.imp.on_reducer(
            "player_teleport_waystone_start",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::PlayerTeleportWaystoneStart { request },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, request)
            }),
        ))
    }
    fn remove_on_player_teleport_waystone_start(
        &self,
        callback: PlayerTeleportWaystoneStartCallbackId,
    ) {
        self.imp
            .remove_on_reducer("player_teleport_waystone_start", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `player_teleport_waystone_start`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_player_teleport_waystone_start {
    /// Set the call-reducer flags for the reducer `player_teleport_waystone_start` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn player_teleport_waystone_start(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_player_teleport_waystone_start for super::SetReducerFlags {
    fn player_teleport_waystone_start(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("player_teleport_waystone_start", flags);
    }
}
