// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct PlayerRespawnArgs {
    pub teleport_home: bool,
}

impl From<PlayerRespawnArgs> for super::Reducer {
    fn from(args: PlayerRespawnArgs) -> Self {
        Self::PlayerRespawn {
            teleport_home: args.teleport_home,
        }
    }
}

impl __sdk::InModule for PlayerRespawnArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `player_respawn`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait player_respawn {
    /// Request that the remote module invoke the reducer `player_respawn` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`player_respawn:player_respawn_then`] to run a callback after the reducer completes.
    fn player_respawn(&self, teleport_home: bool) -> __sdk::Result<()> {
        self.player_respawn_then(teleport_home, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `player_respawn` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn player_respawn_then(
        &self,
        teleport_home: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl player_respawn for super::RemoteReducers {
    fn player_respawn_then(
        &self,
        teleport_home: bool,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(PlayerRespawnArgs { teleport_home }, callback)
    }
}
