// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::column_pad_4_u_64_type::ColumnPad4U64;
use super::experience_stack_f_32_type::ExperienceStackF32;
use super::item_stack_type::ItemStack;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub enum QuestReward {
    PaddingNone(ColumnPad4U64),

    ItemStack(ItemStack),

    Achievement(i32),

    Collectible(i32),

    Experience(ExperienceStackF32),

    SecondaryKnowledge(i32),
}

impl __sdk::InModule for QuestReward {
    type Module = super::RemoteModule;
}
