// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::region_population_loop_timer_type::RegionPopulationLoopTimer;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `region_popuplation_loop_timer`.
///
/// Obtain a handle from the [`RegionPopuplationLoopTimerTableAccess::region_popuplation_loop_timer`] method on [`super::RemoteTables`],
/// like `ctx.db.region_popuplation_loop_timer()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.region_popuplation_loop_timer().on_insert(...)`.
pub struct RegionPopuplationLoopTimerTableHandle<'ctx> {
    imp: __sdk::TableHandle<RegionPopulationLoopTimer>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `region_popuplation_loop_timer`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RegionPopuplationLoopTimerTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RegionPopuplationLoopTimerTableHandle`], which mediates access to the table `region_popuplation_loop_timer`.
    fn region_popuplation_loop_timer(&self) -> RegionPopuplationLoopTimerTableHandle<'_>;
}

impl RegionPopuplationLoopTimerTableAccess for super::RemoteTables {
    fn region_popuplation_loop_timer(&self) -> RegionPopuplationLoopTimerTableHandle<'_> {
        RegionPopuplationLoopTimerTableHandle {
            imp: self
                .imp
                .get_table::<RegionPopulationLoopTimer>("region_popuplation_loop_timer"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RegionPopuplationLoopTimerInsertCallbackId(__sdk::CallbackId);
pub struct RegionPopuplationLoopTimerDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for RegionPopuplationLoopTimerTableHandle<'ctx> {
    type Row = RegionPopulationLoopTimer;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RegionPopulationLoopTimer> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RegionPopuplationLoopTimerInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RegionPopuplationLoopTimerInsertCallbackId {
        RegionPopuplationLoopTimerInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RegionPopuplationLoopTimerInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RegionPopuplationLoopTimerDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RegionPopuplationLoopTimerDeleteCallbackId {
        RegionPopuplationLoopTimerDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RegionPopuplationLoopTimerDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<RegionPopulationLoopTimer>("region_popuplation_loop_timer");
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}
pub struct RegionPopuplationLoopTimerUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RegionPopuplationLoopTimerTableHandle<'ctx> {
    type UpdateCallbackId = RegionPopuplationLoopTimerUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RegionPopuplationLoopTimerUpdateCallbackId {
        RegionPopuplationLoopTimerUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RegionPopuplationLoopTimerUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<RegionPopulationLoopTimer>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<RegionPopulationLoopTimer>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `scheduled_id` unique index on the table `region_popuplation_loop_timer`,
/// which allows point queries on the field of the same name
/// via the [`RegionPopuplationLoopTimerScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.region_popuplation_loop_timer().scheduled_id().find(...)`.
pub struct RegionPopuplationLoopTimerScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RegionPopulationLoopTimer, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RegionPopuplationLoopTimerTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `region_popuplation_loop_timer`.
    pub fn scheduled_id(&self) -> RegionPopuplationLoopTimerScheduledIdUnique<'ctx> {
        RegionPopuplationLoopTimerScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RegionPopuplationLoopTimerScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RegionPopulationLoopTimer> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RegionPopulationLoopTimer`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait region_popuplation_loop_timerQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RegionPopulationLoopTimer`.
    fn region_popuplation_loop_timer(
        &self,
    ) -> __sdk::__query_builder::Table<RegionPopulationLoopTimer>;
}

impl region_popuplation_loop_timerQueryTableAccess for __sdk::QueryTableAccessor {
    fn region_popuplation_loop_timer(
        &self,
    ) -> __sdk::__query_builder::Table<RegionPopulationLoopTimer> {
        __sdk::__query_builder::Table::new("region_popuplation_loop_timer")
    }
}
