// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RentState {
    pub entity_id: u64,
    pub dimension_network_id: u64,
    pub claim_entity_id: u64,
    pub white_list: Vec<u64>,
    pub daily_rent: u32,
    pub paid_rent: u32,
    pub active: bool,
    pub defaulted: bool,
    pub eviction_timestamp: Option<__sdk::Timestamp>,
}

impl __sdk::InModule for RentState {
    type Module = super::RemoteModule;
}
