// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::resource_growth_recipe_desc_type::ResourceGrowthRecipeDesc;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `resource_growth_recipe_desc`.
///
/// Obtain a handle from the [`ResourceGrowthRecipeDescTableAccess::resource_growth_recipe_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.resource_growth_recipe_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_growth_recipe_desc().on_insert(...)`.
pub struct ResourceGrowthRecipeDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<ResourceGrowthRecipeDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `resource_growth_recipe_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ResourceGrowthRecipeDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ResourceGrowthRecipeDescTableHandle`], which mediates access to the table `resource_growth_recipe_desc`.
    fn resource_growth_recipe_desc(&self) -> ResourceGrowthRecipeDescTableHandle<'_>;
}

impl ResourceGrowthRecipeDescTableAccess for super::RemoteTables {
    fn resource_growth_recipe_desc(&self) -> ResourceGrowthRecipeDescTableHandle<'_> {
        ResourceGrowthRecipeDescTableHandle {
            imp: self
                .imp
                .get_table::<ResourceGrowthRecipeDesc>("resource_growth_recipe_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ResourceGrowthRecipeDescInsertCallbackId(__sdk::CallbackId);
pub struct ResourceGrowthRecipeDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for ResourceGrowthRecipeDescTableHandle<'ctx> {
    type Row = ResourceGrowthRecipeDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ResourceGrowthRecipeDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ResourceGrowthRecipeDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceGrowthRecipeDescInsertCallbackId {
        ResourceGrowthRecipeDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ResourceGrowthRecipeDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ResourceGrowthRecipeDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ResourceGrowthRecipeDescDeleteCallbackId {
        ResourceGrowthRecipeDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ResourceGrowthRecipeDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<ResourceGrowthRecipeDesc>("resource_growth_recipe_desc");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}
pub struct ResourceGrowthRecipeDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for ResourceGrowthRecipeDescTableHandle<'ctx> {
    type UpdateCallbackId = ResourceGrowthRecipeDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> ResourceGrowthRecipeDescUpdateCallbackId {
        ResourceGrowthRecipeDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: ResourceGrowthRecipeDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ResourceGrowthRecipeDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ResourceGrowthRecipeDesc>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `resource_growth_recipe_desc`,
/// which allows point queries on the field of the same name
/// via the [`ResourceGrowthRecipeDescIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.resource_growth_recipe_desc().id().find(...)`.
pub struct ResourceGrowthRecipeDescIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ResourceGrowthRecipeDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> ResourceGrowthRecipeDescTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `resource_growth_recipe_desc`.
    pub fn id(&self) -> ResourceGrowthRecipeDescIdUnique<'ctx> {
        ResourceGrowthRecipeDescIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> ResourceGrowthRecipeDescIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<ResourceGrowthRecipeDesc> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ResourceGrowthRecipeDesc`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait resource_growth_recipe_descQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ResourceGrowthRecipeDesc`.
    fn resource_growth_recipe_desc(
        &self,
    ) -> __sdk::__query_builder::Table<ResourceGrowthRecipeDesc>;
}

impl resource_growth_recipe_descQueryTableAccess for __sdk::QueryTableAccessor {
    fn resource_growth_recipe_desc(
        &self,
    ) -> __sdk::__query_builder::Table<ResourceGrowthRecipeDesc> {
        __sdk::__query_builder::Table::new("resource_growth_recipe_desc")
    }
}
