// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_retrieve_lost_item_request_type::PlayerRetrieveLostItemRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RetrieveLostItemArgs {
    pub request: PlayerRetrieveLostItemRequest,
}

impl From<RetrieveLostItemArgs> for super::Reducer {
    fn from(args: RetrieveLostItemArgs) -> Self {
        Self::RetrieveLostItem {
            request: args.request,
        }
    }
}

impl __sdk::InModule for RetrieveLostItemArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `retrieve_lost_item`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait retrieve_lost_item {
    /// Request that the remote module invoke the reducer `retrieve_lost_item` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`retrieve_lost_item:retrieve_lost_item_then`] to run a callback after the reducer completes.
    fn retrieve_lost_item(&self, request: PlayerRetrieveLostItemRequest) -> __sdk::Result<()> {
        self.retrieve_lost_item_then(request, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `retrieve_lost_item` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn retrieve_lost_item_then(
        &self,
        request: PlayerRetrieveLostItemRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl retrieve_lost_item for super::RemoteReducers {
    fn retrieve_lost_item_then(
        &self,
        request: PlayerRetrieveLostItemRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RetrieveLostItemArgs { request }, callback)
    }
}
