// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetQuestTrackedArgs {
    pub id: i32,
    pub tracked: bool,
}

impl From<SetQuestTrackedArgs> for super::Reducer {
    fn from(args: SetQuestTrackedArgs) -> Self {
        Self::SetQuestTracked {
            id: args.id,
            tracked: args.tracked,
        }
    }
}

impl __sdk::InModule for SetQuestTrackedArgs {
    type Module = super::RemoteModule;
}

pub struct SetQuestTrackedCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_quest_tracked`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_quest_tracked {
    /// Request that the remote module invoke the reducer `set_quest_tracked` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_set_quest_tracked`] callbacks.
    fn set_quest_tracked(&self, id: i32, tracked: bool) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `set_quest_tracked`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`SetQuestTrackedCallbackId`] can be passed to [`Self::remove_on_set_quest_tracked`]
    /// to cancel the callback.
    fn on_set_quest_tracked(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &i32, &bool) + Send + 'static,
    ) -> SetQuestTrackedCallbackId;
    /// Cancel a callback previously registered by [`Self::on_set_quest_tracked`],
    /// causing it not to run in the future.
    fn remove_on_set_quest_tracked(&self, callback: SetQuestTrackedCallbackId);
}

impl set_quest_tracked for super::RemoteReducers {
    fn set_quest_tracked(&self, id: i32, tracked: bool) -> __sdk::Result<()> {
        self.imp
            .call_reducer("set_quest_tracked", SetQuestTrackedArgs { id, tracked })
    }
    fn on_set_quest_tracked(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &i32, &bool) + Send + 'static,
    ) -> SetQuestTrackedCallbackId {
        SetQuestTrackedCallbackId(self.imp.on_reducer(
            "set_quest_tracked",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::SetQuestTracked { id, tracked },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, id, tracked)
            }),
        ))
    }
    fn remove_on_set_quest_tracked(&self, callback: SetQuestTrackedCallbackId) {
        self.imp.remove_on_reducer("set_quest_tracked", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `set_quest_tracked`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_set_quest_tracked {
    /// Set the call-reducer flags for the reducer `set_quest_tracked` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn set_quest_tracked(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_set_quest_tracked for super::SetReducerFlags {
    fn set_quest_tracked(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("set_quest_tracked", flags);
    }
}
