// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::loot_rarity_desc_type::LootRarityDesc;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StageLootRarityDescArgs {
    pub records: Vec<LootRarityDesc>,
}

impl From<StageLootRarityDescArgs> for super::Reducer {
    fn from(args: StageLootRarityDescArgs) -> Self {
        Self::StageLootRarityDesc {
            records: args.records,
        }
    }
}

impl __sdk::InModule for StageLootRarityDescArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `stage_loot_rarity_desc`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait stage_loot_rarity_desc {
    /// Request that the remote module invoke the reducer `stage_loot_rarity_desc` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`stage_loot_rarity_desc:stage_loot_rarity_desc_then`] to run a callback after the reducer completes.
    fn stage_loot_rarity_desc(&self, records: Vec<LootRarityDesc>) -> __sdk::Result<()> {
        self.stage_loot_rarity_desc_then(records, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `stage_loot_rarity_desc` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn stage_loot_rarity_desc_then(
        &self,
        records: Vec<LootRarityDesc>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl stage_loot_rarity_desc for super::RemoteReducers {
    fn stage_loot_rarity_desc_then(
        &self,
        records: Vec<LootRarityDesc>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(StageLootRarityDescArgs { records }, callback)
    }
}
