// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::traveler_task_knowledge_requirement_desc_type::TravelerTaskKnowledgeRequirementDesc;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StageTravelerTaskKnowledgeRequirementDescArgs {
    pub records: Vec<TravelerTaskKnowledgeRequirementDesc>,
}

impl From<StageTravelerTaskKnowledgeRequirementDescArgs> for super::Reducer {
    fn from(args: StageTravelerTaskKnowledgeRequirementDescArgs) -> Self {
        Self::StageTravelerTaskKnowledgeRequirementDesc {
            records: args.records,
        }
    }
}

impl __sdk::InModule for StageTravelerTaskKnowledgeRequirementDescArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `stage_traveler_task_knowledge_requirement_desc`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait stage_traveler_task_knowledge_requirement_desc {
    /// Request that the remote module invoke the reducer `stage_traveler_task_knowledge_requirement_desc` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`stage_traveler_task_knowledge_requirement_desc:stage_traveler_task_knowledge_requirement_desc_then`] to run a callback after the reducer completes.
    fn stage_traveler_task_knowledge_requirement_desc(
        &self,
        records: Vec<TravelerTaskKnowledgeRequirementDesc>,
    ) -> __sdk::Result<()> {
        self.stage_traveler_task_knowledge_requirement_desc_then(records, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `stage_traveler_task_knowledge_requirement_desc` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn stage_traveler_task_knowledge_requirement_desc_then(
        &self,
        records: Vec<TravelerTaskKnowledgeRequirementDesc>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl stage_traveler_task_knowledge_requirement_desc for super::RemoteReducers {
    fn stage_traveler_task_knowledge_requirement_desc_then(
        &self,
        records: Vec<TravelerTaskKnowledgeRequirementDesc>,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            StageTravelerTaskKnowledgeRequirementDescArgs { records },
            callback,
        )
    }
}
