// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::pillar_shaping_desc_type::PillarShapingDesc;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StagePillarShapingDescArgs {
    pub records: Vec<PillarShapingDesc>,
}

impl From<StagePillarShapingDescArgs> for super::Reducer {
    fn from(args: StagePillarShapingDescArgs) -> Self {
        Self::StagePillarShapingDesc {
            records: args.records,
        }
    }
}

impl __sdk::InModule for StagePillarShapingDescArgs {
    type Module = super::RemoteModule;
}

pub struct StagePillarShapingDescCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `stage_pillar_shaping_desc`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait stage_pillar_shaping_desc {
    /// Request that the remote module invoke the reducer `stage_pillar_shaping_desc` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_stage_pillar_shaping_desc`] callbacks.
    fn stage_pillar_shaping_desc(&self, records: Vec<PillarShapingDesc>) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `stage_pillar_shaping_desc`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`StagePillarShapingDescCallbackId`] can be passed to [`Self::remove_on_stage_pillar_shaping_desc`]
    /// to cancel the callback.
    fn on_stage_pillar_shaping_desc(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Vec<PillarShapingDesc>) + Send + 'static,
    ) -> StagePillarShapingDescCallbackId;
    /// Cancel a callback previously registered by [`Self::on_stage_pillar_shaping_desc`],
    /// causing it not to run in the future.
    fn remove_on_stage_pillar_shaping_desc(&self, callback: StagePillarShapingDescCallbackId);
}

impl stage_pillar_shaping_desc for super::RemoteReducers {
    fn stage_pillar_shaping_desc(&self, records: Vec<PillarShapingDesc>) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "stage_pillar_shaping_desc",
            StagePillarShapingDescArgs { records },
        )
    }
    fn on_stage_pillar_shaping_desc(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec<PillarShapingDesc>) + Send + 'static,
    ) -> StagePillarShapingDescCallbackId {
        StagePillarShapingDescCallbackId(self.imp.on_reducer(
            "stage_pillar_shaping_desc",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::StagePillarShapingDesc { records },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, records)
            }),
        ))
    }
    fn remove_on_stage_pillar_shaping_desc(&self, callback: StagePillarShapingDescCallbackId) {
        self.imp
            .remove_on_reducer("stage_pillar_shaping_desc", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `stage_pillar_shaping_desc`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_stage_pillar_shaping_desc {
    /// Set the call-reducer flags for the reducer `stage_pillar_shaping_desc` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn stage_pillar_shaping_desc(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_stage_pillar_shaping_desc for super::SetReducerFlags {
    fn stage_pillar_shaping_desc(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("stage_pillar_shaping_desc", flags);
    }
}
