// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::gate_desc_type::GateDesc;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `staged_gate_desc`.
///
/// Obtain a handle from the [`StagedGateDescTableAccess::staged_gate_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.staged_gate_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.staged_gate_desc().on_insert(...)`.
pub struct StagedGateDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<GateDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `staged_gate_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StagedGateDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StagedGateDescTableHandle`], which mediates access to the table `staged_gate_desc`.
    fn staged_gate_desc(&self) -> StagedGateDescTableHandle<'_>;
}

impl StagedGateDescTableAccess for super::RemoteTables {
    fn staged_gate_desc(&self) -> StagedGateDescTableHandle<'_> {
        StagedGateDescTableHandle {
            imp: self.imp.get_table::<GateDesc>("staged_gate_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StagedGateDescInsertCallbackId(__sdk::CallbackId);
pub struct StagedGateDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StagedGateDescTableHandle<'ctx> {
    type Row = GateDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = GateDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StagedGateDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StagedGateDescInsertCallbackId {
        StagedGateDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StagedGateDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StagedGateDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StagedGateDescDeleteCallbackId {
        StagedGateDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StagedGateDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<GateDesc>("staged_gate_desc");
    _table.add_unique_constraint::<i32>("building_id", |row| &row.building_id);
}
pub struct StagedGateDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StagedGateDescTableHandle<'ctx> {
    type UpdateCallbackId = StagedGateDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StagedGateDescUpdateCallbackId {
        StagedGateDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StagedGateDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<GateDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<GateDesc>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `building_id` unique index on the table `staged_gate_desc`,
/// which allows point queries on the field of the same name
/// via the [`StagedGateDescBuildingIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.staged_gate_desc().building_id().find(...)`.
pub struct StagedGateDescBuildingIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<GateDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StagedGateDescTableHandle<'ctx> {
    /// Get a handle on the `building_id` unique index on the table `staged_gate_desc`.
    pub fn building_id(&self) -> StagedGateDescBuildingIdUnique<'ctx> {
        StagedGateDescBuildingIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("building_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StagedGateDescBuildingIdUnique<'ctx> {
    /// Find the subscribed row whose `building_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<GateDesc> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `GateDesc`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait staged_gate_descQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `GateDesc`.
    fn staged_gate_desc(&self) -> __sdk::__query_builder::Table<GateDesc>;
}

impl staged_gate_descQueryTableAccess for __sdk::QueryTableAccessor {
    fn staged_gate_desc(&self) -> __sdk::__query_builder::Table<GateDesc> {
        __sdk::__query_builder::Table::new("staged_gate_desc")
    }
}
