// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::clothing_desc_type::ClothingDesc;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct StageClothingDescArgs {
    pub records: Vec<ClothingDesc>,
}

impl From<StageClothingDescArgs> for super::Reducer {
    fn from(args: StageClothingDescArgs) -> Self {
        Self::StageClothingDesc {
            records: args.records,
        }
    }
}

impl __sdk::InModule for StageClothingDescArgs {
    type Module = super::RemoteModule;
}

pub struct StageClothingDescCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `stage_clothing_desc`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait stage_clothing_desc {
    /// Request that the remote module invoke the reducer `stage_clothing_desc` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_stage_clothing_desc`] callbacks.
    fn stage_clothing_desc(&self, records: Vec<ClothingDesc>) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `stage_clothing_desc`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`StageClothingDescCallbackId`] can be passed to [`Self::remove_on_stage_clothing_desc`]
    /// to cancel the callback.
    fn on_stage_clothing_desc(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Vec<ClothingDesc>) + Send + 'static,
    ) -> StageClothingDescCallbackId;
    /// Cancel a callback previously registered by [`Self::on_stage_clothing_desc`],
    /// causing it not to run in the future.
    fn remove_on_stage_clothing_desc(&self, callback: StageClothingDescCallbackId);
}

impl stage_clothing_desc for super::RemoteReducers {
    fn stage_clothing_desc(&self, records: Vec<ClothingDesc>) -> __sdk::Result<()> {
        self.imp
            .call_reducer("stage_clothing_desc", StageClothingDescArgs { records })
    }
    fn on_stage_clothing_desc(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec<ClothingDesc>) + Send + 'static,
    ) -> StageClothingDescCallbackId {
        StageClothingDescCallbackId(self.imp.on_reducer(
            "stage_clothing_desc",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::StageClothingDesc { records },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, records)
            }),
        ))
    }
    fn remove_on_stage_clothing_desc(&self, callback: StageClothingDescCallbackId) {
        self.imp
            .remove_on_reducer("stage_clothing_desc", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `stage_clothing_desc`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_stage_clothing_desc {
    /// Set the call-reducer flags for the reducer `stage_clothing_desc` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn stage_clothing_desc(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_stage_clothing_desc for super::SetReducerFlags {
    fn stage_clothing_desc(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("stage_clothing_desc", flags);
    }
}
