// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::item_list_desc_type::ItemListDesc;
use super::item_list_possibility_type::ItemListPossibility;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `staged_item_list_desc`.
///
/// Obtain a handle from the [`StagedItemListDescTableAccess::staged_item_list_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.staged_item_list_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.staged_item_list_desc().on_insert(...)`.
pub struct StagedItemListDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<ItemListDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `staged_item_list_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StagedItemListDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StagedItemListDescTableHandle`], which mediates access to the table `staged_item_list_desc`.
    fn staged_item_list_desc(&self) -> StagedItemListDescTableHandle<'_>;
}

impl StagedItemListDescTableAccess for super::RemoteTables {
    fn staged_item_list_desc(&self) -> StagedItemListDescTableHandle<'_> {
        StagedItemListDescTableHandle {
            imp: self.imp.get_table::<ItemListDesc>("staged_item_list_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StagedItemListDescInsertCallbackId(__sdk::CallbackId);
pub struct StagedItemListDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StagedItemListDescTableHandle<'ctx> {
    type Row = ItemListDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ItemListDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StagedItemListDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StagedItemListDescInsertCallbackId {
        StagedItemListDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StagedItemListDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StagedItemListDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StagedItemListDescDeleteCallbackId {
        StagedItemListDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StagedItemListDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ItemListDesc>("staged_item_list_desc");
    _table.add_unique_constraint::<i32>("id", |row| &row.id);
}
pub struct StagedItemListDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StagedItemListDescTableHandle<'ctx> {
    type UpdateCallbackId = StagedItemListDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StagedItemListDescUpdateCallbackId {
        StagedItemListDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StagedItemListDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<ItemListDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ItemListDesc>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `staged_item_list_desc`,
/// which allows point queries on the field of the same name
/// via the [`StagedItemListDescIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.staged_item_list_desc().id().find(...)`.
pub struct StagedItemListDescIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<ItemListDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StagedItemListDescTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `staged_item_list_desc`.
    pub fn id(&self) -> StagedItemListDescIdUnique<'ctx> {
        StagedItemListDescIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StagedItemListDescIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<ItemListDesc> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ItemListDesc`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait staged_item_list_descQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ItemListDesc`.
    fn staged_item_list_desc(&self) -> __sdk::__query_builder::Table<ItemListDesc>;
}

impl staged_item_list_descQueryTableAccess for __sdk::QueryTableAccessor {
    fn staged_item_list_desc(&self) -> __sdk::__query_builder::Table<ItemListDesc> {
        __sdk::__query_builder::Table::new("staged_item_list_desc")
    }
}
