// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::buff_effect_type::BuffEffect;
use super::food_desc_type::FoodDesc;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `staged_food_desc`.
///
/// Obtain a handle from the [`StagedFoodDescTableAccess::staged_food_desc`] method on [`super::RemoteTables`],
/// like `ctx.db.staged_food_desc()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.staged_food_desc().on_insert(...)`.
pub struct StagedFoodDescTableHandle<'ctx> {
    imp: __sdk::TableHandle<FoodDesc>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `staged_food_desc`.
///
/// Implemented for [`super::RemoteTables`].
pub trait StagedFoodDescTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`StagedFoodDescTableHandle`], which mediates access to the table `staged_food_desc`.
    fn staged_food_desc(&self) -> StagedFoodDescTableHandle<'_>;
}

impl StagedFoodDescTableAccess for super::RemoteTables {
    fn staged_food_desc(&self) -> StagedFoodDescTableHandle<'_> {
        StagedFoodDescTableHandle {
            imp: self.imp.get_table::<FoodDesc>("staged_food_desc"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct StagedFoodDescInsertCallbackId(__sdk::CallbackId);
pub struct StagedFoodDescDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for StagedFoodDescTableHandle<'ctx> {
    type Row = FoodDesc;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FoodDesc> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = StagedFoodDescInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StagedFoodDescInsertCallbackId {
        StagedFoodDescInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: StagedFoodDescInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = StagedFoodDescDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> StagedFoodDescDeleteCallbackId {
        StagedFoodDescDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: StagedFoodDescDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FoodDesc>("staged_food_desc");
    _table.add_unique_constraint::<i32>("item_id", |row| &row.item_id);
}
pub struct StagedFoodDescUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for StagedFoodDescTableHandle<'ctx> {
    type UpdateCallbackId = StagedFoodDescUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> StagedFoodDescUpdateCallbackId {
        StagedFoodDescUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: StagedFoodDescUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<FoodDesc>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FoodDesc>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `item_id` unique index on the table `staged_food_desc`,
/// which allows point queries on the field of the same name
/// via the [`StagedFoodDescItemIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.staged_food_desc().item_id().find(...)`.
pub struct StagedFoodDescItemIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FoodDesc, i32>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> StagedFoodDescTableHandle<'ctx> {
    /// Get a handle on the `item_id` unique index on the table `staged_food_desc`.
    pub fn item_id(&self) -> StagedFoodDescItemIdUnique<'ctx> {
        StagedFoodDescItemIdUnique {
            imp: self.imp.get_unique_constraint::<i32>("item_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> StagedFoodDescItemIdUnique<'ctx> {
    /// Find the subscribed row whose `item_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &i32) -> Option<FoodDesc> {
        self.imp.find(col_val)
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `FoodDesc`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait staged_food_descQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `FoodDesc`.
    fn staged_food_desc(&self) -> __sdk::__query_builder::Table<FoodDesc>;
}

impl staged_food_descQueryTableAccess for __sdk::QueryTableAccessor {
    fn staged_food_desc(&self) -> __sdk::__query_builder::Table<FoodDesc> {
        __sdk::__query_builder::Table::new("staged_food_desc")
    }
}
