// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::item_stack_type::ItemStack;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TradeOrderState {
    pub entity_id: u64,
    pub shop_entity_id: u64,
    pub remaining_stock: i32,
    pub offer_items: Vec<ItemStack>,
    pub offer_cargo_id: Vec<i32>,
    pub required_items: Vec<ItemStack>,
    pub required_cargo_id: Vec<i32>,
    pub traveler_trade_order_id: Option<i32>,
}

impl __sdk::InModule for TradeOrderState {
    type Module = super::RemoteModule;
}
