// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

#![allow(unused, clippy::all)]
use super::trade_pocket_type::TradePocket;
use super::trade_session_state_type::TradeSessionState;
use super::trade_session_status_type::TradeSessionStatus;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `trade_session_state`.
///
/// Obtain a handle from the [`TradeSessionStateTableAccess::trade_session_state`] method on [`super::RemoteTables`],
/// like `ctx.db.trade_session_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.trade_session_state().on_insert(...)`.
pub struct TradeSessionStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<TradeSessionState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `trade_session_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TradeSessionStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TradeSessionStateTableHandle`], which mediates access to the table `trade_session_state`.
    fn trade_session_state(&self) -> TradeSessionStateTableHandle<'_>;
}

impl TradeSessionStateTableAccess for super::RemoteTables {
    fn trade_session_state(&self) -> TradeSessionStateTableHandle<'_> {
        TradeSessionStateTableHandle {
            imp: self
                .imp
                .get_table::<TradeSessionState>("trade_session_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TradeSessionStateInsertCallbackId(__sdk::CallbackId);
pub struct TradeSessionStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for TradeSessionStateTableHandle<'ctx> {
    type Row = TradeSessionState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TradeSessionState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TradeSessionStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TradeSessionStateInsertCallbackId {
        TradeSessionStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TradeSessionStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TradeSessionStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TradeSessionStateDeleteCallbackId {
        TradeSessionStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TradeSessionStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TradeSessionState>("trade_session_state");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}
pub struct TradeSessionStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for TradeSessionStateTableHandle<'ctx> {
    type UpdateCallbackId = TradeSessionStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> TradeSessionStateUpdateCallbackId {
        TradeSessionStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: TradeSessionStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<TradeSessionState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TradeSessionState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `entity_id` unique index on the table `trade_session_state`,
/// which allows point queries on the field of the same name
/// via the [`TradeSessionStateEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.trade_session_state().entity_id().find(...)`.
pub struct TradeSessionStateEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TradeSessionState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> TradeSessionStateTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `trade_session_state`.
    pub fn entity_id(&self) -> TradeSessionStateEntityIdUnique<'ctx> {
        TradeSessionStateEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> TradeSessionStateEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TradeSessionState> {
        self.imp.find(col_val)
    }
}
