// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::player_trade_decline_request_type::PlayerTradeDeclineRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TradeDeclineArgs {
    pub request: PlayerTradeDeclineRequest,
}

impl From<TradeDeclineArgs> for super::Reducer {
    fn from(args: TradeDeclineArgs) -> Self {
        Self::TradeDecline {
            request: args.request,
        }
    }
}

impl __sdk::InModule for TradeDeclineArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `trade_decline`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait trade_decline {
    /// Request that the remote module invoke the reducer `trade_decline` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`trade_decline:trade_decline_then`] to run a callback after the reducer completes.
    fn trade_decline(&self, request: PlayerTradeDeclineRequest) -> __sdk::Result<()> {
        self.trade_decline_then(request, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `trade_decline` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn trade_decline_then(
        &self,
        request: PlayerTradeDeclineRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl trade_decline for super::RemoteReducers {
    fn trade_decline_then(
        &self,
        request: PlayerTradeDeclineRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(TradeDeclineArgs { request }, callback)
    }
}
