// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct TradeCancelServerArgs {
    pub session_entity_id: u64,
    pub resolution_message: String,
}

impl From<TradeCancelServerArgs> for super::Reducer {
    fn from(args: TradeCancelServerArgs) -> Self {
        Self::TradeCancelServer {
            session_entity_id: args.session_entity_id,
            resolution_message: args.resolution_message,
        }
    }
}

impl __sdk::InModule for TradeCancelServerArgs {
    type Module = super::RemoteModule;
}

pub struct TradeCancelServerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `trade_cancel_server`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait trade_cancel_server {
    /// Request that the remote module invoke the reducer `trade_cancel_server` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_trade_cancel_server`] callbacks.
    fn trade_cancel_server(
        &self,
        session_entity_id: u64,
        resolution_message: String,
    ) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `trade_cancel_server`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`TradeCancelServerCallbackId`] can be passed to [`Self::remove_on_trade_cancel_server`]
    /// to cancel the callback.
    fn on_trade_cancel_server(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> TradeCancelServerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_trade_cancel_server`],
    /// causing it not to run in the future.
    fn remove_on_trade_cancel_server(&self, callback: TradeCancelServerCallbackId);
}

impl trade_cancel_server for super::RemoteReducers {
    fn trade_cancel_server(
        &self,
        session_entity_id: u64,
        resolution_message: String,
    ) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "trade_cancel_server",
            TradeCancelServerArgs {
                session_entity_id,
                resolution_message,
            },
        )
    }
    fn on_trade_cancel_server(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64, &String) + Send + 'static,
    ) -> TradeCancelServerCallbackId {
        TradeCancelServerCallbackId(self.imp.on_reducer(
            "trade_cancel_server",
            Box::new(move |ctx: &super::ReducerEventContext| {
                #[allow(irrefutable_let_patterns)]
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::TradeCancelServer {
                                    session_entity_id,
                                    resolution_message,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, session_entity_id, resolution_message)
            }),
        ))
    }
    fn remove_on_trade_cancel_server(&self, callback: TradeCancelServerCallbackId) {
        self.imp
            .remove_on_reducer("trade_cancel_server", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `trade_cancel_server`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_trade_cancel_server {
    /// Set the call-reducer flags for the reducer `trade_cancel_server` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn trade_cancel_server(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_trade_cancel_server for super::SetReducerFlags {
    fn trade_cancel_server(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("trade_cancel_server", flags);
    }
}
