// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateMovingCostArgs {
    pub player_housing_entity_id: u64,
    pub moving_cost: i32,
}

impl From<UpdateMovingCostArgs> for super::Reducer {
    fn from(args: UpdateMovingCostArgs) -> Self {
        Self::UpdateMovingCost {
            player_housing_entity_id: args.player_housing_entity_id,
            moving_cost: args.moving_cost,
        }
    }
}

impl __sdk::InModule for UpdateMovingCostArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_moving_cost`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_moving_cost {
    /// Request that the remote module invoke the reducer `update_moving_cost` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_moving_cost:update_moving_cost_then`] to run a callback after the reducer completes.
    fn update_moving_cost(
        &self,
        player_housing_entity_id: u64,
        moving_cost: i32,
    ) -> __sdk::Result<()> {
        self.update_moving_cost_then(player_housing_entity_id, moving_cost, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_moving_cost` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_moving_cost_then(
        &self,
        player_housing_entity_id: u64,
        moving_cost: i32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl update_moving_cost for super::RemoteReducers {
    fn update_moving_cost_then(
        &self,
        player_housing_entity_id: u64,
        moving_cost: i32,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateMovingCostArgs {
                player_housing_entity_id,
                moving_cost,
            },
            callback,
        )
    }
}
