// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::world_place_building_request_type::WorldPlaceBuildingRequest;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct WorldPlaceBuildingArgs {
    pub request: WorldPlaceBuildingRequest,
}

impl From<WorldPlaceBuildingArgs> for super::Reducer {
    fn from(args: WorldPlaceBuildingArgs) -> Self {
        Self::WorldPlaceBuilding {
            request: args.request,
        }
    }
}

impl __sdk::InModule for WorldPlaceBuildingArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `world_place_building`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait world_place_building {
    /// Request that the remote module invoke the reducer `world_place_building` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`world_place_building:world_place_building_then`] to run a callback after the reducer completes.
    fn world_place_building(&self, request: WorldPlaceBuildingRequest) -> __sdk::Result<()> {
        self.world_place_building_then(request, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `world_place_building` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn world_place_building_then(
        &self,
        request: WorldPlaceBuildingRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()>;
}

impl world_place_building for super::RemoteReducers {
    fn world_place_building_then(
        &self,
        request: WorldPlaceBuildingRequest,

        callback: impl FnOnce(
            &super::ReducerEventContext,
            Result<Result<(), String>, __sdk::InternalError>,
        ) + Send
        + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(WorldPlaceBuildingArgs { request }, callback)
    }
}
