// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::offset_coordinates_small_message_type::OffsetCoordinatesSmallMessage;
use super::world_placement_type_type::WorldPlacementType;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct WorldEntityPlacement {
    pub entity_id: u64,
    pub coordinates: OffsetCoordinatesSmallMessage,
    pub prototype_id: i32,
    pub placement_type: WorldPlacementType,
}

impl __sdk::InModule for WorldEntityPlacement {
    type Module = super::RemoteModule;
}
