// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Location } from "./Location";

export type BuildingStateWithName = {
  entity_id: bigint;
  claim_entity_id: bigint;
  direction_index: number;
  building_description_id: number;
  constructed_by_player_entity_id: bigint;
  building_name: string;
  location: Location | null;
};
