// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pocket } from "./Pocket";

export type Model = {
  entity_id: bigint;
  pockets: Array<Pocket>;
  inventory_index: number;
  cargo_index: number;
  owner_entity_id: bigint;
  player_owner_entity_id: bigint;
  region: string;
};
