name: Check branch changes
on:
  push:
    branches-ignore:
      - main

env:
  TEST_TAG: my-test:test

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - name: Install dependencies
      run: bun install --frozen-lockfile
    - name: Check formatting
      run: bun run format:check
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v1
    - name: Install dependencies
      run: bun install --frozen-lockfile
    - name: Build
      run: bun run build
