name: Check branch changes
on:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  backend_lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust/api-server
    steps:
      - uses: actions/checkout@v4
      - name: Rust setup
        run: rustup toolchain install stable --profile minimal
      - name: Build
        run: cargo fmt --check
  backend_build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rust/api-server
    steps:
    - uses: actions/checkout@v4
    - name: Rust setup
      run: rustup toolchain install stable --profile minimal
    - name: Build
      run: cargo build --release --bin bitcraft-hub-api
